const fs=require('fs'),assert=require('assert');
let harness=fs.readFileSync(__dirname+'/test.cjs','utf8').split("check('offline app")[0];
harness=harness.replace('this.tagName=', 'this.handlers={};this.tagName=').replace('toggle:()=>false','toggle:()=>false,add:()=>{}').replace('addEventListener(){}','addEventListener(n,f){(this.handlers[n]??=[]).push(f)}emit(n,e){for(const f of this.handlers[n]||[])f(e)}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,width:112,height:112}}querySelectorAll(){return ["fire","aim","jump","hook","crouch","reload","weapon","grenade","flash","strike","heavy","pulse","dodge","pickup","door"].map(n=>{const e=els["touch_"+n]||(els["touch_"+n]=new Element());e.dataset.action=n;return e})}');
harness=harness.replace('const doc={','const doc={body:new Element(),').replace('const C={THREE,','const C={matchMedia:()=>({matches:true}),navigator:{userAgent:"Android"},THREE,');
const {A,T,C,els}=new Function('require','__dirname',harness+';return {A,T,C,els};')(require,__dirname);
const checks=[];function check(n,f){f();checks.push(n);console.log('PASS',n)}
function ev(id,x=56,y=56){return {pointerId:id,clientX:x,clientY:y,pointerType:'touch',preventDefault(){}}}
A.start();A.closeShop();T.setMode('combat');
check('mobile initializes without pointer lock',()=>{assert(A.ready);assert.equal(A.getState().mode,'combat')});
check('joystick supports movement and release',()=>{els.moveStick.emit('pointerdown',ev(1,56,10));assert(T.keys.has('KeyW'));assert(T.keys.has('ShiftLeft'));els.moveStick.emit('pointerup',ev(1));assert(!T.keys.has('KeyW'));assert(!T.keys.has('ShiftLeft'))});
check('multi-touch movement, look and held jump coexist independently',()=>{const canvas=els.canvas.children[0];els.moveStick.emit('pointerdown',ev(2,90,56));canvas.emit('pointerdown',ev(3,200,100));els.touch_jump.emit('pointerdown',ev(4));assert(T.keys.has('KeyD'));assert(T.keys.has('Space'));const q=T.camera.quaternion.clone();canvas.emit('pointermove',ev(3,250,120));T.updateCamera(1);assert(!q.equals(T.camera.quaternion));canvas.emit('pointerup',ev(3));assert(T.keys.has('KeyD')&&T.keys.has('Space'));els.touch_jump.emit('pointercancel',ev(4));assert(!T.keys.has('Space'));els.moveStick.emit('pointercancel',ev(2));assert(!T.keys.has('KeyD'))});
check('held firing stops on pointer cancellation',()=>{T.player.hp=10000;const n=A.getState().ammo.pistol;els.touch_fire.emit('pointerdown',ev(5));T.tick(.3);assert.equal(A.getState().ammo.pistol,n-1);els.touch_fire.emit('pointercancel',ev(5));T.tick(.3);assert.equal(A.getState().ammo.pistol,n-1)});
check('pause clears held touch keys and ignores new touch actions',()=>{els.touch_jump.emit('pointerdown',ev(6));A.pause();assert.equal(T.keys.size,0);els.touch_jump.emit('pointerdown',ev(7));assert.equal(T.keys.size,0);A.resume();assert.equal(T.keys.size,0)});
check('mobile grenade button uses existing inventory',()=>{const n=A.getState().grenades;els.touch_grenade.emit('pointerdown',ev(8));assert.equal(A.getState().grenades,n-1);els.touch_grenade.emit('pointerup',ev(8))});
fs.writeFileSync(__dirname+'/evidence/mobile-checks.json',JSON.stringify({passed:true,realDeviceVerified:false,checks},null,2));
