const fs=require('fs'),assert=require('assert');
const harness=fs.readFileSync(__dirname+'/test.cjs','utf8').split("check('offline app")[0];
const {A,T,C}=new Function('require','__dirname',harness+';return {A,T,C};')(require,__dirname);
const X=T.destruction,V=C.THREE.Vector3,checks=[];
function check(name,f){f();checks.push(name);console.log('PASS',name);}
A.start();A.closeShop();
let m=X.machines.find(b=>!b.disabled);
check('machine waits 30 simulated seconds and pause freezes timer',()=>{T.setTime(10);X.hit({body:m},200);X.tick(39.999);assert(!m.disabled);A.pause();T.tick(20);assert.equal(T.getTime(),10);assert(!X.exploded.has(m.machineName));A.resume();T.setTime(40);X.tick(40);assert(m.disabled);assert(X.exploded.has(m.machineName));assert(!X.burning.has(m));assert(!A.getState().machines.includes(m.machineName));assert(!T.loot.some(l=>l.support===m.machineName));assert(!T.factory.machineMeshes.some(o=>o.userData.machineKeys.includes(m.machineName)));});
check('exploded machine never respawns or supplies loot in later waves',()=>{for(let i=0;i<5;i++){T.refreshWaveLayout();assert(m.disabled);assert(!A.getState().machines.includes(m.machineName));assert(!T.loot.some(l=>l.support===m.machineName));}});
check('burn timer and burning machine survive wave change',()=>{const b=X.machines.find(b=>!b.disabled);T.setTime(100);X.hit({body:b},200);T.refreshWaveLayout();assert(X.burning.has(b));assert(!b.disabled);assert.equal(b.burnStart,100);assert(!T.loot.some(l=>l.support===b.machineName));T.setTime(130);X.tick(130);assert(X.exploded.has(b.machineName));});
check('door leaf, frame and upper collision vanish together and reset',()=>{const d=T.factory.doors[0];X.hit({body:T.space.doorPoly(d)},300);assert(!d.frame.visible&&!d.group.visible);assert(T.space.polys.filter(p=>p.doorFrameId===d.id).every(p=>p.disabled));A.start();assert(d.frame.visible&&d.group.visible);assert(T.space.polys.filter(p=>p.doorFrameId===d.id).every(p=>!p.disabled));assert.equal(X.exploded.size,0);assert.equal(X.burning.size,0);});
check('cabinet has 100 HP, loses collision and visual instances at destruction',()=>{const b=X.cabinets[0];assert.equal(b.hp,100);assert(X.hit({body:b},99));assert(!b.disabled);X.hit({body:b},1);assert(b.disabled);assert(!X.hit({body:b},100));A.start();assert.equal(b.hp,100);assert(!b.disabled);});
check('cabinet drop threshold is exactly 25 percent and rolls once',()=>{const math=C.Math||Object.create(Math);C.Math=math;const original=math.random;try{for(const [roll,expected] of [[.249999,1],[.25,0]]){A.start();A.closeShop();const b=X.cabinets[0],before=T.loot.length;math.random=()=>roll;X.hit({body:b},100);assert.equal(T.loot.length-before,expected);X.hit({body:b},100);assert.equal(T.loot.length-before,expected);if(expected){const l=T.loot.at(-1);assert.equal(l.pos.y,.1);assert.equal(l.support,'置物櫃掉落');}}}finally{math.random=original;}});
check('machine explosion damages nearby people and structures through shared blast system',()=>{A.start();A.closeShop();T.setMode('combat');T.player.hp=10000;const b=X.machines.find(b=>!b.disabled),pos=new V((b.minX+b.maxX)/2,.9,(b.minZ+b.maxZ)/2);T.player.pos.copy(pos).y=0;T.setTime(0);X.hit({body:b},200);const old=T.space.clear;T.space.clear=()=>true;const hp=T.player.hp;T.setTime(30);X.tick(30);T.space.clear=old;assert(T.player.hp<hp);assert(b.disabled);});
fs.writeFileSync(__dirname+'/evidence/s110-checks.json',JSON.stringify({passed:true,checks},null,2));
