const fs=require('fs'),vm=require('vm'),assert=require('assert'),base=__dirname;const noop=()=>{};

class Element{constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.style={};this.dataset={};this.classList={toggle:()=>false};this.hidden=false;this.value='1.3';this.ctx=new Proxy({measureText:s=>({width:s.length*8}),createRadialGradient:()=>({addColorStop:noop})},{get:(t,k)=>t[k]||noop});}append(o){this.children.push(o)}appendChild(o){this.append(o)}replaceChildren(){this.children=[]}addEventListener(){}setAttribute(){}getContext(){return this.ctx}click(){this.onclick?.()}requestPointerLock(){return Promise.resolve()}}
const els={},events={},storage=new Map();const doc={getElementById:id=>els[id]||(els[id]=new Element(id==='radar'?'canvas':'div')),createElement:tag=>new Element(tag),addEventListener:noop,exitPointerLock:noop,activeElement:{tagName:'BODY'}};
const THREE={...require('./src/three.min.js')};THREE.WebGLRenderer=class{constructor(){this.domElement=new Element('canvas');this.info={render:{triangles:0,calls:0}}}setPixelRatio(){}setSize(){}render(){}};let now=0;const C={THREE,document:doc,console,performance:{now:()=>now},innerWidth:1280,innerHeight:900,devicePixelRatio:1,requestAnimationFrame:noop,addEventListener:(k,f)=>events[k]=f,setTimeout:noop,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},URL:{},Blob:class{},__SHOOTER_TEST__:true,FLOOR_DATA:JSON.parse(fs.readFileSync(base+'/src/floor3.json')),window:null};C.window=C;vm.createContext(C);for(const f of ['config.js','models.js','factory.js','space.js','action.js','look.js','destruction.js','blessings.js','tactics.js','audio.js','mobile.js','game.js'])vm.runInContext(fs.readFileSync(base+'/src/'+f,'utf8'),C,{filename:f});const A=C.factoryGame,T=A.test,checks=[];function check(name,fn){fn();checks.push(name);console.log('PASS',name)}function tick(s){for(let i=0;i<s*60;i++){now+=1000/60;if(A.getState().mode==='combat')T.player.hp=10000;T.tick(1/60);}}
check('offline app initializes full 3F',()=>{assert(A.ready);assert.equal(C.FLOOR_DATA.objects.filter(x=>x.kind==='machine').length,189)});
check('S1.14 balance values are applied',()=>{assert.equal(A.config.version,'S1.14');assert.equal(A.config.grappleRange,5);assert.equal(A.config.enemyHitChance,.75);assert.equal(A.config.tracerSpeed,80);assert.equal(A.config.tracerRadius,.015)});
console.time('start');A.start();console.timeEnd('start');
check('20-second buy phase and economy',()=>{assert.equal(A.getState().mode,'buy');assert.equal(A.getState().money,2400);A.buy('rifle');assert.equal(A.getState().inventory.main,'rifle');assert.equal(A.getState().money,1000);A.buy('armor');assert.equal(A.getState().armor,100);assert.equal(A.getState().money,350)});
A.closeShop();tick(20.1);
check('wave starts and NPCs spawn on reachable floor',()=>{assert.equal(A.getState().mode,'combat');assert(A.getState().enemies>0);for(const e of T.enemies)assert(!T.space.blocked(e.pos.x,0,e.pos.z,.2,1.7))});
check('combat purchases rejected',()=>{let n=A.getState().money;A.buy('flash');assert.equal(A.getState().money,n)});
check('body armor absorbs, head bypasses',()=>{T.player.hp=100;T.player.armor=100;T.damagePlayer(20);assert.equal(T.player.hp,89);assert.equal(T.player.armor,91);T.damagePlayer(20,true);assert.equal(T.player.hp,69);assert.equal(T.player.armor,91)});
check('damage indicator points toward supplied source',()=>{T.player.hp=100;T.damagePlayer(1,false,new THREE.Vector3(0,0,-4));assert.equal(els.damageDir.style.opacity,'1');assert(els.damageDir.style.transform.includes('rotate('));});
check('ammo consumed and reload restores capacity',()=>{T.player.hp=100;const before=A.getState().ammo.rifle;T.fire();assert.equal(A.getState().ammo.rifle,before-1);T.reload();tick(1.8);assert.equal(A.getState().ammo.rifle,T.stats().mag)});
check('jet fuel rate and ceiling collision',()=>{T.player.hp=100;T.player.pos.copy(new THREE.Vector3(...C.FLOOR_DATA.spawn.slice(0,1),0,C.FLOOR_DATA.spawn[1]));T.player.fuel=100;T.keys.add('Space');tick(1);assert(Math.abs(T.player.fuel-50)<2);assert(T.player.pos.y>0);assert(T.player.pos.y>1.8);assert(T.player.pos.y<=4.28);T.keys.delete('Space');tick(1);});
check('fuel recharges 10 percentage points per grounded second',()=>{T.player.fuel=0;T.player.pos.y=0;T.player.vy=0;tick(1);assert(Math.abs(T.player.fuel-10)<1);});
check('weapon levels improve all four stats and unlock element',()=>{const before=T.stats('rifle');T.gain('rifle',400);const after=T.stats('rifle');assert(after.damage>before.damage);assert(after.mag>before.mag);assert(after.recoil<before.recoil);assert(after.crit>before.crit);assert(after.elementChance>0)});
check('drops expire at ten seconds',()=>{T.dropWeapon('rifle',T.player.pos);const d=T.drops.at(-1);assert(Math.abs(d.end-T.getTime()-10)<.001);tick(10.1);assert(!T.drops.includes(d));});
check('weapon XP survives death/restart, money resets',()=>{let xp=A.getState().xp.rifle;T.damagePlayer(10000,true);assert.equal(A.getState().mode,'dead');A.start();assert.equal(A.getState().xp.rifle,xp);assert.equal(A.getState().money,2400)});
check('pause freezes countdown',()=>{const before=A.getState().buyTime;A.pause();tick(3);assert.equal(A.getState().buyTime,before);A.resume();});
const report={passed:true,browserGPUVerified:false,checks,final:A.getState()};fs.writeFileSync(base+'/evidence/logic-checks.json',JSON.stringify(report,null,2));console.log('CHECKS',checks.length);
// Deterministic additional mechanic tests on actual 3F geometry.
A.closeShop();T.setMode('combat');T.keys.clear();T.enemies.splice(0).forEach(e=>T.scene.remove(e.model.group));
check('full flame effect removes 15% maximum HP over five seconds',()=>{const e={pos:T.player.pos.clone(),hp:10000,maxHP:1000,status:{},hit:0};T.applyStatus(e,'火',false,'pistol');const code=fs.readFileSync(base+'/src/game.js','utf8');/* exercise production status tick on real enemy */T.spawnEnemy();const actor=T.enemies[0];actor.hp=1000;actor.maxHP=1000;actor.cooldown=999;actor.pos.copy(T.player.pos).add(new THREE.Vector3(12,0,0));T.applyStatus(actor,'火',false,'pistol');tick(5.05);assert(Math.abs(actor.hp-850)<.001);});
check('repeat status refreshes duration without multiplying strength',()=>{const a=T.player;T.applyStatus(a,'水',false,'smg');const end=a.status['水'].end;T.setTime(T.getTime()+1);T.applyStatus(a,'水',false,'smg');assert.equal(a.status['水'].end,end+1);assert.equal(Object.keys(a.status).filter(k=>k==='水').length,1);T.applyStatus(a,'雷',false,'pistol');assert(a.status['雷']&&a.status['水']);a.status={};});
check('barrel chain reaction and hook full damage',()=>{T.player.hp=100;T.player.armor=0;T.barrels.forEach(b=>{b.exploded=true;b.hp=0;b.mesh.visible=false});const p=T.player.pos.clone().add(new THREE.Vector3(0,0,.5)),b=T.makeBarrel(p);const b2=T.makeBarrel(p.clone().add(new THREE.Vector3(.4,0,0)));T.explodeBarrel(b,true,'pistol',true);assert(b.exploded);assert(b2.exploded);assert.equal(T.player.hp,0);assert.equal(A.getState().mode,'dead');});
A.start();A.closeShop();T.setMode('combat');
check('grenades and flashbangs spawn ballistic projectiles',()=>{let n=T.projectiles.length;T.throwItem('grenade');T.throwItem('flash');assert.equal(T.projectiles.length,n+2);tick(2.5);assert.equal(T.projectiles.length,0);});
check('hook latch cancels on release with three-second cooldown',()=>{let found=null;const p=T.player.pos.clone().add(new THREE.Vector3(0,1.25,0));for(let y=0;y<6.28;y+=.04){const dir=new THREE.Vector3(-Math.sin(y),0,-Math.cos(y)),h=T.space.cast(p,dir,2.7);if(h&&h.kind!=='floor'&&h.kind!=='ceiling'){found=y;break;}}assert.notEqual(found,null);T.setView(found,0);T.keys.add('KeyV');T.startHook();T.endHook();assert.equal(A.getState().cooldown,3);T.keys.delete('KeyV');});
check('ray stops at cabinet, wall and door volumes; open rack gaps are not solid boxes',()=>{const rack=C.FLOOR_DATA.objects.find(o=>o.kind==='rack'),r=T.space.polys.filter(p=>p.kind==='rack');assert(r.length>0);assert(r.some(p=>p.hi-p.lo<.04));assert(r.some(p=>p.hi===1.8));const wall=T.space.polys.find(p=>p.kind==='wall');const mid=new THREE.Vector3((wall.minX+wall.maxX)/2,1,(wall.minZ+wall.maxZ)/2);const hit=T.space.cast(mid.clone().add(new THREE.Vector3(0,0,-2)),new THREE.Vector3(0,0,1),4);assert(hit);});
fs.writeFileSync(base+'/evidence/logic-checks.json',JSON.stringify({passed:true,browserGPUVerified:false,checks,final:A.getState()},null,2));

check('picking up a same-type gun retains XP and replaces magazine',()=>{T.tactics.clear();T.loot.length=0;T.drops.splice(0).forEach(d=>T.scene.remove(d.mesh));T.enemies.forEach(e=>e.cooldown=999);T.dropWeapon('rifle',T.player.pos);const xp=A.getState().xp.rifle;tick(.05);T.pickup();assert.equal(A.getState().active,'rifle');assert.equal(A.getState().xp.rifle,xp);assert(A.getState().ammo.rifle>0);});
check('clearing wave awards cash and reopens twenty-second shop',()=>{T.setMode('combat');while(A.getState().remaining>0)assert(T.spawnEnemy());const money=A.getState().money;for(const e of T.enemies)if(e.hp>0)T.hurtEnemy(e,1e8,true,'rifle');tick(.1);assert.equal(A.getState().mode,'buy');assert.equal(A.getState().wave,2);assert(A.getState().money>money);assert(A.getState().buyTime>19.8);});
check('floor and ceiling rays respect the 4.5m shell',()=>{const origin=T.player.pos.clone().setY(1.2);const a=T.space.cast(origin,new THREE.Vector3(0,-1,0),2),b=T.space.cast(origin,new THREE.Vector3(0,1,0),6);assert(a&&b);assert.equal(a.kind,'floor');assert.equal(b.kind,'ceiling');assert(Math.abs(a.distance-1.2)<.001);assert(Math.abs(b.distance-3.3)<.001);});
check('ceiling fixture batch count remains bounded',()=>{let batches=0;T.scene.traverse(o=>{if(o.name==='Ceiling')o.traverse(c=>{if(c.isMesh)batches++});});assert(batches<=6);});
fs.writeFileSync(base+'/evidence/logic-checks.json',JSON.stringify({passed:true,browserGPUVerified:false,checks,final:A.getState()},null,2));

// Export actual runtime scene + production camera for a CPU geometry inspection only.
A.start();A.closeShop();T.setMode('combat');T.updateCamera(1);T.scene.updateMatrixWorld(true);const triangles=[],matrix=new THREE.Matrix4(),world=new THREE.Matrix4(),p=new THREE.Vector3();T.scene.traverse(o=>{if(!o.isMesh)return;let a=o;while(a){if(!a.visible)return;a=a.parent;}const g=o.geometry,pos=g.attributes.position,idx=g.index;if(!pos)return;const n=o.isInstancedMesh?o.count:1;for(let k=0;k<n;k++){if(o.isInstancedMesh){o.getMatrixAt(k,matrix);world.multiplyMatrices(o.matrixWorld,matrix);}else world.copy(o.matrixWorld);for(let j=0;j<(idx?idx.count:pos.count);j+=3){for(let m=0;m<3;m++){p.fromBufferAttribute(pos,idx?idx.getX(j+m):j+m).applyMatrix4(world);triangles.push(p.x,p.y,p.z);}const c=o.material.color?.clone().convertLinearToSRGB()||new THREE.Color(0xffffff);triangles.push(c.r,c.g,c.b,0);}}});fs.writeFileSync(base+'/evidence/scene-triangles.bin',Buffer.from(new Float32Array(triangles).buffer));const target=new THREE.Vector3();T.camera.getWorldDirection(target);target.add(T.camera.position);fs.writeFileSync(base+'/evidence/camera.json',JSON.stringify({eye:T.camera.position.toArray(),target:target.toArray(),fov:T.camera.fov}));console.log('ALL',checks.length);
