const fs=require('fs'),assert=require('assert');
const harness=fs.readFileSync(__dirname+'/test.cjs','utf8').split("check('offline app")[0];
const {A,T,C}=new Function('require','__dirname',harness+';return {A,T,C};')(require,__dirname);
const checks=[];function check(name,f){f();checks.push(name);console.log('PASS',name)}
function combat(w){A.start();for(let i=1;i<w;i++)T.beginBuy();A.closeShop();T.setMode('combat');T.tick(.01);return T.enemies.find(e=>e.creeper);}
function close(e){e.pos.copy(T.player.pos);e.fuseEnd=null;e.flash=0;}
check('no creeper before wave ten; exactly one additional enemy on wave ten',()=>{combat(9);assert.equal(A.getState().creepers,0);T.beginBuy();assert.equal(A.getState().creepers,0);A.closeShop();T.setMode('combat');T.tick(.01);assert.equal(A.getState().creepers,1);const e=T.enemies.find(e=>e.creeper);assert(!e.boss);assert(!T.space.blocked(e.pos.x,0,e.pos.z));const remaining=A.getState().remaining;for(let i=0;i<10;i++)T.tick(.01);assert.equal(A.getState().creepers,1);assert.equal(A.getState().remaining,remaining);});
check('blocked proximity does not start fuse',()=>{const e=T.enemies.find(e=>e.creeper),clear=T.space.clear;close(e);T.space.clear=()=>false;try{T.tickCreeper(e,0);assert.equal(e.fuseEnd,null);}finally{T.space.clear=clear;}});
check('two-second fuse pauses with game and damage uses HP at detonation',()=>{const e=T.enemies.find(e=>e.creeper);close(e);T.setTime(100);T.player.hp=100;T.player.armor=100;T.tickCreeper(e,0);assert.equal(e.fuseEnd,102);A.pause();T.tick(10);assert.equal(T.getTime(),100);A.resume();T.setTime(101.999);T.tickCreeper(e,0);assert.equal(T.player.hp,100);T.player.hp=73;T.setTime(102);T.tickCreeper(e,0);assert.equal(T.player.hp,7.3);assert.equal(T.player.armor,100);assert.equal(e.hp,0);assert(!e.model.group.visible);T.tickCreeper(e,1);assert.equal(T.player.hp,7.3);});
check('detonated creeper is not replaced in same wave',()=>{T.player.hp=100;T.tick(.01);assert.equal(A.getState().creepers,0);});
check('wave twenty gets one creeper, escape outside blast avoids damage',()=>{const e=combat(20);assert(e);close(e);T.tickCreeper(e,0);e.pos.x+=7;T.setTime(e.fuseEnd);T.player.hp=100;T.tickCreeper(e,0);assert.equal(T.player.hp,100);assert.equal(e.hp,0);});
check('cover blocks blast after fuse starts',()=>{T.spawnEnemy(true);const e=T.enemies.filter(e=>e.creeper&&e.hp>0)[0];close(e);T.tickCreeper(e,0);T.setTime(e.fuseEnd);const clear=T.space.clear;T.space.clear=()=>false;try{T.player.hp=60;T.tickCreeper(e,0);assert.equal(T.player.hp,60);}finally{T.space.clear=clear;}});
check('killing armed creeper cancels detonation and drops no gun',()=>{T.spawnEnemy(true);const e=T.enemies.find(e=>e.creeper&&e.hp>0);close(e);T.tickCreeper(e,0);const n=T.drops.length;T.hurtEnemy(e,1e6,true,'pistol');T.setTime(e.fuseEnd+1);T.player.hp=100;T.tickCreeper(e,1);assert.equal(T.player.hp,100);assert.equal(T.drops.length,n);});
check('living armed creeper does not block wave clear and is removed',()=>{T.spawnEnemy(true);const e=T.enemies.find(e=>e.creeper&&e.hp>0);close(e);T.tickCreeper(e,0);while(A.getState().remaining>0)assert(T.spawnEnemy());for(const other of T.enemies)if(!other.creeper)T.hurtEnemy(other,1e6,false);const w=A.getState().wave;T.tick(.01);assert.equal(A.getState().mode,'buy');assert.equal(A.getState().wave,w+1);assert(!T.enemies.some(e=>e.creeper));assert(!T.scene.children.includes(e.model.group));});
check('wave thirty has a creeper and still spawns normal third-wave boss',()=>{const e=combat(30);assert(e);while(A.getState().remaining>0)assert(T.spawnEnemy());assert.equal(T.enemies.filter(e=>e.creeper).length,1);assert.equal(T.enemies.filter(e=>e.boss).length,1);});
check('practice and restart have no creeper; exit removes armed actor',()=>{const e=T.enemies.find(e=>e.creeper);close(e);T.tickCreeper(e,0);A.leave();assert(!T.enemies.length);A.startPractice();assert.equal(A.getState().enemies,5);assert.equal(A.getState().creepers,0);A.start();assert.equal(A.getState().wave,1);assert.equal(A.getState().creepers,0);});
fs.writeFileSync(__dirname+'/evidence/creeper-checks.json',JSON.stringify({passed:true,browserVerified:false,checks},null,2));
