const fs=require('fs'),assert=require('assert');
let harness=fs.readFileSync(__dirname+'/test.cjs','utf8').split("check('offline app")[0];
harness=harness.replace('this.tagName=', 'this.handlers={};this.tagName=').replace('this.style={}', 'this.style={setProperty(k,v){this[k]=v}}').replace('toggle:()=>false','toggle:()=>false,add:()=>{}').replace('addEventListener(){}',`addEventListener(n,f){(this.handlers[n]??=[]).push(f)}emit(n,e){for(const f of this.handlers[n]||[])f(e)}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,width:120,height:120}}querySelectorAll(){return ["fire","fireLeft","aim","jump","hook","crouch","reload","weapon","grenade","flash","strike","heavy","pulse","dodge","interact","skills","throws"].map(n=>{const e=els["touch_"+n]||(els["touch_"+n]=new Element());e.dataset.action=n;return e})}`);
harness=harness.replace('const doc={','const doc={body:new Element(),').replace('const C={THREE,','const C={matchMedia:()=>({matches:true}),navigator:{userAgent:"Android"},THREE,');
const {A,T,C,els,events,storage}=new Function('require','__dirname',harness+';return {A,T,C,els,events,storage};')(require,__dirname);
const checks=[];function check(n,f){f();checks.push(n);console.log('PASS',n)}
function ev(id,x=60,y=60){return {pointerId:id,clientX:x,clientY:y,pointerType:'touch',preventDefault(){}}}
const down=(name,id,x,y)=>els['touch_'+name].emit('pointerdown',ev(id,x,y));
const up=(name,id)=>els['touch_'+name].emit('pointerup',ev(id));
const UI=T.getTouchUI();A.start();A.closeShop();T.setMode('combat');T.updateHUD();
check('mobile initializes and analog joystick has deadzone and gradual speed',()=>{assert(A.ready);els.moveStick.emit('pointerdown',ev(1,61,60));assert.equal(T.getTouchMove().x,0);els.moveStick.emit('pointermove',ev(1,80,60));const m=T.getTouchMove();assert(m.x>0&&m.x<1);assert(T.keys.has('KeyD'));els.moveStick.emit('pointermove',ev(1,60,15));assert(T.keys.has('ShiftLeft'));els.moveStick.emit('pointerup',ev(1));assert(!T.getTouchMove().active);assert(!T.keys.has('ShiftLeft'));});
check('two thumbs can move, fire and aim simultaneously',()=>{els.moveStick.emit('pointerdown',ev(2,100,60));const q=T.camera.quaternion.clone(),n=A.getState().ammo.pistol;down('fire',3,700,220);els.touch_fire.emit('pointermove',ev(3,740,240));T.updateCamera(1);assert(!q.equals(T.camera.quaternion));assert(T.keys.has('KeyD'));assert.equal(A.getState().ammo.pistol,n-1);up('fire',3);assert(T.keys.has('KeyD'));els.moveStick.emit('pointerup',ev(2));});
check('aim and crouch toggle on tap without holding a finger',()=>{down('aim',4);up('aim',4);assert(T.getAim());down('crouch',5);up('crouch',5);assert(T.keys.has('ControlLeft'));down('aim',6);up('aim',6);assert(!T.getAim());down('crouch',7);up('crouch',7);assert(!T.keys.has('ControlLeft'));});
check('independent left and right firing pointers do not prematurely release',()=>{T.player.hp=10000;down('fire',8);down('fireLeft',9);up('fire',8);const n=A.getState().ammo.pistol;T.tick(.5);assert.equal(A.getState().ammo.pistol,n-1);els.touch_fireLeft.emit('pointercancel',ev(9));const m=A.getState().ammo.pistol;T.tick(.5);assert.equal(A.getState().ammo.pistol,m);});
check('camera drag and jump remain independent; cancellation releases jump',()=>{const canvas=els.canvas.children[0];canvas.emit('pointerdown',ev(10,700,150));down('jump',11);const q=T.camera.quaternion.clone();canvas.emit('pointermove',ev(10,750,170));T.updateCamera(1);assert(!q.equals(T.camera.quaternion));canvas.emit('pointerup',ev(10));assert(T.keys.has('Space'));els.touch_jump.emit('lostpointercapture',ev(11));assert(!T.keys.has('Space'));});
check('utility trays are exclusive and grenades require selection',()=>{els.throwTray.hidden=els.utilityTray.hidden=true;const n=A.getState().grenades;down('throws',12);up('throws',12);assert(!els.throwTray.hidden);assert.equal(A.getState().grenades,n);down('skills',13);up('skills',13);assert(els.throwTray.hidden&&!els.utilityTray.hidden);down('throws',14);up('throws',14);down('grenade',15);up('grenade',15);assert.equal(A.getState().grenades,n-1);assert(els.throwTray.hidden&&els.utilityTray.hidden);});
check('pause, orientation and death clear every held control',()=>{down('aim',16);up('aim',16);down('jump',17);A.pause();assert.equal(T.keys.size,0);assert(!T.getAim());down('fire',18);assert.equal(UI.state().held,0);A.resume();down('hook',19);events.orientationchange();assert.equal(T.keys.size,0);assert.equal(UI.state().held,0);down('jump',20);T.damagePlayer(1e6,true);assert.equal(A.getState().mode,'dead');assert.equal(UI.state().held,0);});
check('settings pause the game, persist preferences and resume correctly',()=>{A.startPractice();UI.openSettings();assert.equal(A.getState().mode,'paused');assert(!els.touchSettings.hidden);els.touch_size.oninput({target:{value:'110'}});els.touch_sensitivity.oninput({target:{value:'130'}});els.touch_leftFire.onchange({target:{checked:true}});assert.equal(JSON.parse(storage.get('factory-touch-v2')).size,110);assert.equal(els.leftFire.hidden,false);UI.closeSettings();assert.equal(A.getState().mode,'combat');assert(els.touchSettings.hidden);A.leave();UI.openSettings();UI.closeSettings();assert.equal(A.getState().mode,'menu');});
check('context interaction appears only when available and weapon actions reflect state',()=>{A.startPractice();UI.update({interaction:'開門',ammo:8,mag:12,gun:'P9',hasMain:false,grenades:0,flashes:1,combat:true,reloading:false});assert(!els.touchInteraction.hidden);assert(els.touch_grenade.disabled);assert(els.touch_weapon.disabled);UI.update({interaction:'',ammo:12,mag:12,gun:'P9',hasMain:true,grenades:1,flashes:1,combat:true,reloading:false});assert(els.touchInteraction.hidden);assert(els.touch_reload.disabled);});
fs.writeFileSync(__dirname+'/evidence/mobile-checks.json',JSON.stringify({passed:true,realDeviceVerified:false,checks},null,2));
