const fs=require('fs'),assert=require('assert');
const harness=fs.readFileSync(__dirname+'/test.cjs','utf8').split("check('offline app")[0];
const {A,T,C}=new Function('require','__dirname',harness+';return {A,T,C};')(require,__dirname);
const V=C.THREE.Vector3,X=T.destruction,S=T.space,checks=[];
function check(name,f){f();checks.push(name);console.log('PASS',name);}
A.start();A.closeShop();
function rayFor(d){const body=S.doorPoly(d);for(let i=0;i<4;i++){let a=body.p[i],b=body.p[(i+1)%4];const normal=new V(b[1]-a[1],0,a[0]-b[0]).normalize();for(const sign of [-1,1]){const origin=new V((a[0]+b[0])/2,1,(a[1]+b[1])/2).addScaledVector(normal,.1*sign),dir=normal.clone().multiplyScalar(-sign),hit=S.cast(origin,dir,.2);if(hit?.door===d)return {origin,dir,hit};}}return null;}
check('all doors share wall HP and display a damage label',()=>{assert(X.doors.length>0);assert(X.doors.every(b=>b.hp===A.config.wallHP));assert(X.label({body:X.doors[0]}).includes('300 / 300 HP'));});
check('hinged and sliding doors retain HP across opening poses then disappear from rays',()=>{for(const type of ['sliding','hinged']){const d=T.factory.doors.find(d=>type==='sliding'?d.type==='sliding':d.type!=='sliding');assert(d);let r=rayFor(d);assert(r);X.hit(r.hit,100);d.t=.65;r=rayFor(d);assert(r);assert.equal(r.hit.body.hp,200);X.hit(r.hit,199);assert(d.group.visible);assert.equal(d.body.hp,1);X.hit(r.hit,1);assert(d.destroyed);assert(!d.group.visible);assert.notEqual(S.cast(r.origin,r.dir,.2)?.door,d);assert(!X.hit(r.hit,1));assert(S.doorPoly(d).disabled);}});
check('destroyed doors remove their movement blocking volume',()=>{let found=false;for(const d of T.factory.doors){X.reset();const b=S.doorPoly(d),p=new V(b.p.reduce((s,p)=>s+p[0],0)/4,0,b.p.reduce((s,p)=>s+p[1],0)/4);if(!S.blocked(p.x,0,p.z,.01,1.7,false)){assert(S.blocked(p.x,0,p.z,.01,1.7));X.hit({body:b},300);assert(!S.blocked(p.x,0,p.z,.01,1.7));found=true;break;}}assert(found);});
check('blast damages the current pose of an open door',()=>{X.reset();let found=false;for(const d of T.factory.doors){d.t=.5;const r=rayFor(d);if(!r)continue;X.blast(r.origin,1,600);if(d.destroyed){found=true;break;}}assert(found);});
check('door damage persists between waves and resets on restart',()=>{const d=T.factory.doors.find(d=>d.destroyed);assert(d);T.beginBuy();assert(d.destroyed);A.start();assert(T.factory.doors.every(d=>!d.destroyed&&d.group.visible&&d.body.hp===300));});
check('flash clears actual chasing enemy memory and hearing cannot restore it while blind',()=>{A.closeShop();T.setMode('combat');assert(T.spawnEnemy());const e=T.enemies.at(-1);e.pos.copy(T.player.pos).add(new V(.4,0,0));e.lastKnown=T.player.pos.clone();e.lastSeen=T.getTime();e.searchEnd=999;e.awareness='追擊';e.visible=true;e.route=[T.player.pos.clone()];T.flash(e.pos.clone().add(new V(0,1.5,0)));assert(e.flash>0);assert.equal(e.lastKnown,null);assert.equal(e.searchEnd,0);assert(!e.visible);assert.equal(e.route.length,0);T.tactics.hear(T.player.pos,20);T.tactics.think(e,.01);assert.equal(e.lastKnown,null);assert.equal(e.awareness,'巡邏');});
check('an enemy must reacquire line of sight after blindness ends',()=>{const e=T.enemies.at(-1);e.flash=0;const clear=S.clear;S.clear=()=>false;T.tactics.think(e,.01);assert(!e.visible);assert.equal(e.lastKnown,null);S.clear=()=>true;T.tactics.think(e,.01);assert(e.visible);assert(e.lastKnown);assert.equal(e.awareness,'追擊');S.clear=clear;});
check('audio absence does not break gameplay or explosions',()=>{T.battleAudio.gun('sniper');T.battleAudio.explosion(4);T.battleAudio.flash(4);assert(A.ready);});
fs.writeFileSync(__dirname+'/evidence/s19-checks.json',JSON.stringify({passed:true,checks},null,2));
