const fs=require('fs'),assert=require('assert');
const harness=fs.readFileSync(__dirname+'/test.cjs','utf8').split("check('offline app")[0];
const {A,T,C,events}=new Function('require','__dirname',harness+';return {A,T,C,events};')(require,__dirname);
const V=C.THREE.Vector3,checks=[];function check(n,f){f();checks.push(n);console.log('PASS',n);}
A.start();A.closeShop();T.setMode('combat');T.spawnEnemy();const enemy=T.enemies[0];
check('new explosion settings are 150, 200 and 6m',()=>{assert.equal(A.config.grenadeDamage,150);assert.equal(A.config.barrelDamage,200);assert.equal(A.config.barrelRadius,6);});
check('new enemy starts with no knowledge of player position',()=>{assert.equal(enemy.awareness,'巡邏');assert.equal(enemy.lastKnown,null);});
let pair;for(const p of T.space.candidates(T.player.pos,0,100)){const q=p.clone().add(new V(0,0,4));if(!T.space.blocked(q.x,0,q.z)&&T.space.clear(p.clone().setY(1.36),q.clone().setY(1.15))){pair=[p,q];break;}}assert(pair);
check('vision requires facing, and last seen position is a snapshot',()=>{enemy.pos.copy(pair[1]);T.player.pos.copy(pair[0]);enemy.facing=Math.PI;T.tactics.think(enemy,.01);assert(!enemy.visible);assert.equal(enemy.lastKnown,null);enemy.facing=0;T.tactics.think(enemy,.01);assert(enemy.visible);const last=enemy.lastKnown.clone();T.player.pos.add(new V(100,0,100));T.tactics.think(enemy,.01);assert(!enemy.visible);assert.equal(enemy.awareness,'搜索');assert(enemy.lastKnown.equals(last));T.setTime(16);T.tactics.think(enemy,.01);assert.equal(enemy.lastKnown,null);assert.equal(enemy.awareness,'巡邏');});
check('nearby noise gives a search point without permanent tracking',()=>{T.player.pos.copy(pair[0]);enemy.visible=false;T.tactics.hear(T.player.pos);assert.equal(enemy.awareness,'搜索');assert(enemy.lastKnown.equals(T.player.pos));T.player.pos.x+=1;assert(!enemy.lastKnown.equals(T.player.pos));});
check('boss on third wave has 1.2x model and twice normal patrol HP',()=>{T.beginBuy();T.beginBuy();while(A.getState().remaining>0)assert(T.spawnEnemy());const boss=T.enemies.find(e=>e.boss);assert(boss);assert.equal(boss.maxHP,65*(1+(A.getState().wave-1)*.1)*2);assert(!boss.model.weapon.visible);T.setMode('combat');T.tick(.001);assert(Math.abs(boss.model.group.scale.x-1.2)<.001);});
check('boss grenade lights up only after touching floor',()=>{const boss=T.enemies.find(e=>e.boss);boss.lastKnown=pair[0].clone();T.throwBossGrenade(boss);const p=T.projectiles.at(-1);assert(p.boss);assert(!p.glow);p.pos.copy(pair[0]).setY(.13);p.v.set(0,-2,0);T.tickEffects(.05);assert(p.glow);assert(p.mesh.material.emissiveIntensity>0);});
check('AGV has 50 HP, ignores player guns but takes other attacks',()=>{const a=T.tactics.getAGV();assert(a);assert.equal(a.hp,50);assert.equal(T.tactics.damageAGV(100,'playerGun'),false);assert.equal(a.hp,50);assert(T.tactics.damageAGV(10,'enemyGun'));assert.equal(a.hp,40);T.tactics.damageAGV(5,'melee');assert.equal(a.hp,35);});
check('AGV follows a path and supplies are collectible once each',()=>{let a=T.tactics.getAGV();T.player.pos.copy(a.pos).add(new V(100,0,100));const start=a.pos.clone();for(let i=0;i<600;i++){T.setTime(T.getTime()+.02);T.tactics.tickAGV(.02);}assert(a.pos.distanceTo(start)>.05);T.player.pos.copy(a.pos);T.player.hp=50;T.player.armor=0;for(let i=0;i<3;i++)assert(T.tactics.supply());assert(!T.tactics.supply());assert.equal(a.supplies,0);T.tactics.damageAGV(100,'explosion');assert.equal(a.hp,0);const stopped=a.pos.clone();T.tactics.tickAGV(1);assert(a.pos.equals(stopped));});
check('swept movement cannot tunnel through a wall',()=>{let found;for(const p of T.space.candidates(pair[0],0,100)){for(let y=0;y<6.28;y+=.4){const dir=new V(-Math.sin(y),0,-Math.cos(y)),h=T.space.cast(p.clone().setY(1),dir,1.2);if(h?.kind==='wall'){found={p,dir,h};break;}}if(found)break;}assert(found);T.player.pos.copy(found.p);T.moveActor(T.player,found.dir.x*4,0,found.dir.z*4);assert(!T.space.blocked(T.player.pos.x,0,T.player.pos.z));});
check('Z/X/C input activates skills; Alt dodge does not crouch',()=>{A.start();A.closeShop();T.setMode('combat');const press=code=>events.keydown({code,repeat:false,preventDefault(){}});T.actions.reset();press('KeyZ');assert(T.actions.state().attacking);T.actions.reset();press('KeyX');assert(T.actions.state().attacking);assert.equal(T.actions.state().energy,80);T.actions.reset();press('KeyC');assert(T.actions.state().pulseCooldown>0);T.actions.reset();press('AltLeft');assert(T.actions.dashing());T.tick(.01);assert.equal(T.avatar.group.scale.y,1);});

fs.writeFileSync(__dirname+'/evidence/tactics-checks.json',JSON.stringify({passed:true,browserGPUVerified:false,checks},null,2));
