(async()=>{'use strict';
const $=id=>document.getElementById(id),T=THREE,D=window.FLOOR_DATA||(await fetch('src/floor3.json').then(r=>{if(!r.ok)throw Error('無法讀取廠區');return r.json();})),W=StrikeCore.WEAPONS,MODES=StrikeCore.MODES;
D.plan=[];
const mobile=location.search.includes('touch=1')||matchMedia('(pointer:coarse)').matches||/Android|iPhone|iPad|iPod/i.test(navigator.userAgent),uiOnly=location.search.includes('ui=1');document.body.classList.toggle('mobile',mobile);
const defaults={quality:mobile?'low':'high',fov:90,sensitivity:100,ads:55,volume:65,touchSize:100,leftFire:false,showFPS:true,motion:true};let settings={...defaults};try{const v=JSON.parse(localStorage.getItem('factory-strike-settings-v1')||'{}');for(const k in defaults)if(typeof v[k]===typeof defaults[k])settings[k]=v[k];}catch(e){}for(const [k,min,max]of [['fov',70,110],['sensitivity',30,180],['ads',20,120],['volume',0,100],['touchSize',85,115]])settings[k]=clamp(settings[k],min,max);if(!['low','medium','high','ultra'].includes(settings.quality))settings.quality=defaults.quality;
const audio=makeStrikeAudio(),actorModels=new Map(),projectileModels=new Map(),dropModels=new Map(),flagModels=[],smokeModels=new Map(),fx=[],decals=[],feed=[];let renderer=null,scene=null,camera=null,visual=null,F=null,S=null,core=null,M=null,input=null,sun=null,previewClock=0,last=0,accumulator=0,hudTimer=0,radarTimer=0,hitEnd=0,hurtEnd=0,toastEnd=0,selectedMode='tdm',lastOptions=null,booted=false,menuShown=true,scoreHeld=false,pauseLock=false,fps=60,frameCount=0,fpsClock=0,qualityRatio=1,deathTarget=null;
const V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),teamColor=t=>t===0?'#62c9f7':'#ff8b7d',seconds=n=>Math.floor(Math.max(0,n)/60).toString().padStart(2,'0')+':'+Math.floor(Math.max(0,n)%60).toString().padStart(2,'0');
const brief={waves:'單人守住廠區：第一波 6 名敵人，每波增加 2 名，分批進場，最多同時 8 名。清空本波後補滿生命、防具與彈藥，準備 20 秒；按 Enter 可提前開始。陣亡即結算完成波數。',tdm:'持續重生的正面對抗。率先取得 50 次擊殺，或 8 分鐘結束時領先的一隊獲勝。注意側翼，與隊友一起控制走道。',ts:'每回合只有一次生命。殲滅敵隊取得一勝，先取得 5 勝即獲勝。陣亡後觀戰隊友，下一回合重新配發裝備。',ctf:'前往敵方基地奪旗，帶回自己的基地得分。自己的旗必須在基地，才能完成交旗；落地旗幟 20 秒後自動歸位。',bomb:'攻方在 A 或 B 點按住 F 3 秒安裝炸彈，守方按住 F 5 秒拆除。引爆倒數 40 秒，每回合交換攻守，先取得 5 勝獲勝。'};
function toast(text,duration=3){$('toast').textContent=text;$('toast').hidden=false;toastEnd=performance.now()/1000+duration;}
function updateWeaponInfo(){const w=W[$('primaryWeapon').value];$('gunStats').textContent='傷害 '+w.damage+(w.pellets?' × '+w.pellets:'')+'　│　彈匣 '+w.mag+'　│　'+Math.round(60/w.interval)+' RPM';}
for(const [id,w]of Object.entries(W))if(!['pistol','knife'].includes(id)){const o=document.createElement('option');o.value=id;o.textContent=w.name+' / '+w.label;$('primaryWeapon').append(o);}updateWeaponInfo();$('primaryWeapon').onchange=updateWeaponInfo;$('modeBrief').textContent=brief.tdm;
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{selectedMode=b.dataset.mode;for(const c of document.querySelectorAll('[data-mode]'))c.classList.toggle('selected',c===b);$('modeBrief').textContent=brief[selectedMode];for(const id of ['teamSize','team','friendlyFire'])$(id).disabled=selectedMode==='waves';$('matchBadge').textContent=selectedMode==='waves'?'單人生存 · 敵人逐波進攻':'玩家 + AI 隊伍對戰';};
function saveSettings(){try{localStorage.setItem('factory-strike-settings-v1',JSON.stringify(settings));}catch(e){}}
function applySettings(){for(const k in defaults){const e=$(k);if(typeof defaults[k]==='boolean')e.checked=settings[k];else e.value=settings[k];if($(k+'Value'))$(k+'Value').textContent=settings[k]+(k==='fov'?'°':'%');}document.documentElement.style.setProperty('--touch-scale',settings.touchSize/100);$('leftFireTouch').hidden=!settings.leftFire;audio.setVolume(settings.volume/100);if(renderer){qualityRatio={low:.85,medium:1,high:1.35,ultra:1.8}[settings.quality];renderer.setPixelRatio(Math.min(devicePixelRatio,qualityRatio));renderer.shadowMap.enabled=['high','ultra'].includes(settings.quality);sun.shadow.mapSize.set(settings.quality==='ultra'?2048:1024,settings.quality==='ultra'?2048:1024);sun.shadow.map?.dispose();sun.shadow.map=null;renderer.setSize(innerWidth,innerHeight);}}
for(const k in defaults)$(k).addEventListener(typeof defaults[k]==='boolean'?'change':'input',e=>{settings[k]=typeof defaults[k]==='boolean'?e.target.checked:typeof defaults[k]==='number'?+e.target.value:e.target.value;saveSettings();applySettings();});$('resetSettings').onclick=()=>{settings={...defaults};saveSettings();applySettings();};$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});};
function lock(){if(mobile||uiOnly)return;try{const p=renderer.domElement.requestPointerLock();p?.catch?.(()=>toast('請點擊遊戲畫面以控制視角',4));}catch(e){toast('請點擊遊戲畫面以控制視角',4);}}
function allowed(){return !!M&&!menuShown&&!M.paused&&['active','warmup'].includes(M.phase)&&M.player.hp>0&&$('scorePanel').hidden&&$('mapPanel').hidden;}
function pause(){if(!$('mapPanel').hidden){$('mapPanel').hidden=true;resume();return;}if(menuShown||M?.phase==='ended')return;if(!$('settings').hidden||!$('help').hidden)return;if(M.paused){resume();return;}M.paused=true;input?.reset();$('pause').hidden=false;pauseLock=true;document.exitPointerLock?.();audio.stop();}
function resume(){if(!M)return;M.paused=false;$('pause').hidden=true;input.reset();audio.unlock();lock();pauseLock=false;last=performance.now();}
function modalOpen(id){if(!menuShown&&!M.paused)pause();$(id).hidden=false;}
$('openSettings').onclick=()=>$('settings').hidden=false;$('pauseSettings').onclick=()=>modalOpen('settings');$('closeSettings').onclick=()=>$('settings').hidden=true;$('openHelp').onclick=()=>$('help').hidden=false;$('pauseHelp').onclick=()=>modalOpen('help');$('closeHelp').onclick=()=>$('help').hidden=true;$('pauseButton').onclick=pause;$('resume').onclick=resume;
function clearEffects(){for(const e of fx){scene?.remove(e.mesh);e.mesh.geometry?.dispose();e.mesh.material?.dispose();}fx.length=0;for(const m of decals){scene?.remove(m);m.geometry.dispose();m.material.dispose();}decals.length=0;for(const map of [projectileModels,dropModels,smokeModels]){for(const m of map.values()){scene?.remove(m);if(map!==dropModels)m.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});}map.clear();}for(const m of flagModels)scene?.remove(m);flagModels.length=0;}
function leave(){M.paused=false;M.phase='menu';menuShown=true;input.reset();document.exitPointerLock?.();$('menu').hidden=false;for(const id of ['hud','touch','pause','scorePanel','death','settings','help','mapPanel'])$(id).hidden=true;$('damage').style.opacity='0';$('flash').style.opacity='0';for(const model of actorModels.values())model.remove();actorModels.clear();clearEffects();feed.length=0;audio.stop();}
$('leave').onclick=leave;$('resultLeave').onclick=leave;for(const b of document.querySelectorAll('[data-command]'))b.onclick=()=>{core.command(b.dataset.command);resume();};
function deploy(practice=false,repeat=false){if(!booted)return;audio.unlock();const gear=$('gear').value;const opts=repeat?lastOptions:{mode:practice?'practice':selectedMode,teamSize:+$('teamSize').value,difficulty:+$('difficulty').value,team:+$('team').value,friendlyFire:$('friendlyFire').checked,loadout:{primary:$('primaryWeapon').value,vest:gear!=='recon',helmet:gear!=='medic',medic:gear==='medic'}};lastOptions=opts;for(const model of actorModels.values())model.remove();actorModels.clear();clearEffects();feed.length=0;M=core.start(opts);M.paused=false;menuShown=false;for(const id of ['menu','pause','scorePanel','death'])$(id).hidden=true;$('hud').hidden=false;$('touch').hidden=!mobile;visual?.addObjectives(M);if(visual)for(const a of M.actors)if(!a.human)actorModels.set(a.id,visual.actor(a.team));input.reset();accumulator=0;last=performance.now();if(M.mode==='ctf'&&visual)for(const f of M.flags){const g=new T.Group();visual.tube(g,0x99a8af,0,.8,0,.025,1.6).rotation.x=0;visual.cube(g,f.team===0?0x46bdf2:0xf47665,.25,1.35,0,.5,.35,.022);scene.add(g);flagModels.push(g);}lock();updateHUD();}
$('deploy').onclick=()=>deploy();$('practice').onclick=()=>deploy(true);$('rematch').onclick=()=>deploy(false,true);$('nextWave').onclick=()=>{audio.unlock();if(core.startWave())lock();};
function renderScores(){if(!M)return;const p=M.player,ended=M.phase==='ended';$('scoreTitle').textContent=ended?(M.result.winner===null?'平手':M.result.winner===p.team?'任務勝利':'任務失敗'):'對戰戰績';$('closeScores').hidden=ended;$('rematch').hidden=!ended;$('resultLeave').hidden=!ended;if(M.mode==='waves'){$('scoreTitle').textContent=ended?'防線失守':'波次生存戰績';$('scoreContent').innerHTML='<div class="result-score">'+M.wave.completed+' <small>波完成</small></div><p>目前第 '+M.wave.number+' 波 · 生存 '+seconds(M.time)+'</p><div class="stat-cards"><span><b>'+p.kills+'</b><small>擊倒敵人</small></span><span><b>'+Math.round(p.shots?p.hits/p.shots*100:0)+'%</b><small>命中率</small></span><span><b>'+Math.round(p.damage)+'</b><small>傷害</small></span></div>';return;}let html='<div class="result-score"><span class="blue-text">'+M.scores[0]+'</span> : <span class="red-text">'+M.scores[1]+'</span></div>';if(ended)html+='<div class="stat-cards"><span><b>'+p.kills+'</b><small>擊殺</small></span><span><b>'+p.deaths+'</b><small>死亡</small></span><span><b>'+Math.round(p.shots?p.hits/p.shots*100:0)+'%</b><small>命中率</small></span><span><b>'+Math.round(p.damage)+'</b><small>傷害</small></span></div>';for(const t of [0,1]){html+='<h3 style="color:'+teamColor(t)+'">'+(t===0?'BLUE':'RED')+' TEAM</h3><table><thead><tr><th>隊員</th><th>K</th><th>D</th><th>A</th><th>旗</th><th>狀態</th></tr></thead><tbody>';for(const a of M.actors.filter(a=>a.team===t).sort((a,b)=>b.kills-a.kills))html+='<tr class="'+(a.human?'you':'')+'"><td>'+a.name+(a.human?' ◂':'')+'</td><td>'+a.kills+'</td><td>'+a.deaths+'</td><td>'+a.assists+'</td><td>'+a.captures+'</td><td>'+(a.hp>0?'存活':'陣亡')+'</td></tr>';html+='</tbody></table>';}if(uiOnly)html+='<p>介面測試模式（未渲染 3D）</p>';$('scoreContent').innerHTML=html;}
function scores(show,hold=false){if(!M||menuShown)return;if(M.phase==='ended')return;scoreHeld=hold&&show;$('scorePanel').hidden=!show;if(show){input.reset();renderScores();if(!hold)document.exitPointerLock?.();}else if(!M.paused)lock();}
function mapOpen(){if(menuShown)return;input.reset();$('mapPanel').hidden=false;mapBackground($('fullMap'),true,M.player);document.exitPointerLock?.();if(!M.paused){M.paused=true;audio.stop();}}$('showMap').onclick=mapOpen;$('closeMap').onclick=()=>{$('mapPanel').hidden=true;resume();};
$('showScores').onclick=()=>scores(true);$('closeScores').onclick=()=>scores(false);
function spatial(pos){if(!M?.player)return [1,0];const d=pos.clone().sub(M.player.pos),distance=d.length(),right=V(Math.cos(M.player.facing),0,-Math.sin(M.player.facing));return [Math.min(1,1/(1+distance*.12)),distance>0?d.normalize().dot(right):0];}
function effect(pos,color,count=5,speed=2,life=.45){if(!scene)return;const budget=mobile?70:settings.quality==='low'?90:180;for(let i=0;i<count&&fx.length<budget;i++){const m=new T.Mesh(new T.SphereGeometry(.018+Math.random()*.028,5,4),new T.MeshBasicMaterial({color,transparent:true,depthWrite:false}));m.position.copy(pos);scene.add(m);fx.push({mesh:m,vel:V((Math.random()-.5)*speed,Math.random()*speed,(Math.random()-.5)*speed),life,total:life,kind:'particle'});}}
function tracer(from,to,team){if(!scene||fx.length>180)return;const g=new T.BufferGeometry().setFromPoints([from,to]),m=new T.Line(g,new T.LineBasicMaterial({color:team===M.player.team?0xffdc96:0xff9175,transparent:true,opacity:.4,depthWrite:false}));scene.add(m);fx.push({mesh:m,life:.06,total:.06,kind:'line'});}
function bulletMark(e){if(!scene||!e.normal||e.hit||decals.length>(mobile?24:80))return;const mesh=new T.Mesh(new T.CircleGeometry(.025+Math.random()*.015,7),new T.MeshBasicMaterial({color:0x24313a,transparent:true,opacity:.65,depthWrite:false,polygonOffset:true,polygonOffsetFactor:-1}));mesh.position.copy(e.to).addScaledVector(e.normal,.006);mesh.quaternion.setFromUnitVectors(V(0,0,1),e.normal);scene.add(mesh);decals.push(mesh);}
function onEvent(e){const p=M?.player,a=M?.actors?.find(a=>a.id===e.actor);if(e.type==='shot'){if(e.first){const [gain,pan]=spatial(e.from);audio.gun(e.weapon,gain,pan);if(a?.human)visual?.fireView();}if(scene&&e.weapon!=='knife'){if(!a?.human||Math.random()<.32)tracer(e.from,e.to,a?.team);if(e.hit)effect(e.to,0xa13e36,3,1.2,.24);else{effect(e.to,0xe8b671,2,1.4,.22);bulletMark(e);}}}
 else if(e.type==='hurt'){if(e.by===p?.id){hitEnd=performance.now()/1000+.13;$('hitmarker').style.borderColor=e.zone==='head'?'#f4bd68':'#fff';}if(e.actor===p?.id){hurtEnd=performance.now()/1000+.5;const attacker=M.actors.find(a=>a.id===e.by);if(attacker){const d=attacker.pos.clone().sub(p.pos);const angle=Math.atan2(d.x,d.z)+p.facing+Math.PI;$('direction').style.transform='translate(-50%,-50%) rotate('+(-angle)+'rad)';}}}
 else if(e.type==='kill'){feed.push({...e,until:performance.now()/1000+6});if(feed.length>5)feed.shift();if(e.by===p?.id){audio.cue('kill');toast((e.weapon==='sniper'?'精準擊殺':'擊倒目標')+'  +1',1.4);}if(e.actor===p?.id){input.reset();deathTarget=null;}}
 else if(e.type==='explosion'){const [gain,pan]=spatial(e.pos);if(e.kind==='flash')audio.flash(gain,pan);else{audio.explosion(gain,pan);effect(e.pos,0xf4b66c,mobile?16:40,6,.65);effect(e.pos,0x58606a,12,2,1.2);}}
 else if(e.type==='step'){if(a){const [g,pan]=spatial(a.pos);audio.step(g*(a.human?.09:.17),pan);}}
 else if(e.type==='reload'||e.type==='reloaded'||e.type==='switch'){if(a){const [g,pan]=spatial(a.pos);audio.reload(g*.15,pan);}}
 else if(e.type==='bounce'){const [g,pan]=spatial(e.pos);audio.reload(g*.13,pan);}
 else if(e.type==='wavePrepare'){input?.reset();toast('第 '+e.wave+' 波準備 · '+e.total+' 名敵人\n生命與彈藥已補充',4);}else if(e.type==='throwReady'){if(a?.human)audio.reload(.18,0);}else if(e.type==='live'){audio.cue('live');toast(M?.mode==='waves'?'第 '+M.wave.number+' 波開始':M?.mode==='practice'?'練習開始 · 五名移動目標':'行動開始',2);}
 else if(e.type==='roundEnd'){toast((e.winner===null?'平手':e.winner===p?.team?'回合勝利':'回合失敗')+'\n'+e.reason,4);input?.reset();}
 else if(e.type==='roundStart'){toast('第 '+e.round+' 回合',2);}
 else if(e.type==='matchEnd'){input?.reset();document.exitPointerLock?.();renderScores();$('scorePanel').hidden=false;}
 else if(e.type==='flagTaken')toast((e.team===p?.team?'我方旗幟被奪走':'已取得敵方旗幟'),3);
 else if(e.type==='capture'){audio.cue('live');toast((e.team===p?.team?'我方':'敵方')+'成功交旗',3);}
 else if(e.type==='flagReturn')toast((e.team===p?.team?'我方':'敵方')+'旗幟歸位',2);
 else if(e.type==='planted'){toast('炸彈已安裝 · 40 秒後引爆',4);audio.cue('live');}
 else if(e.type==='bandaged')a?.human&&toast('包紮完成 · 已止血',2);
 else if(e.type==='heal')e.actor===p?.id&&toast('隊友治療',2);
 else if(e.type==='walljump')a?.human&&toast('WALL JUMP',.8);
 else if(e.type==='command')toast({follow:'隊伍跟隨你',hold:'隊伍守住目前位置',attack:'隊伍進攻目標'}[e.command],2);
}
function action(name){if(name==='cancelThrow'){core?.cancelThrow(M?.player);return true;}if(!allowed()||!M.player.hp)return false;const p=M.player;if(name.startsWith('prepareThrow:'))return core.prepareThrow(p,name.split(':')[1]);if(name==='releaseThrow')return core.releaseThrow(p);if(name==='startWave')return core.startWave();if(name==='reload')core.reload(p);else if(name==='bandage'){if(!core.bandage(p))toast('目前沒有需要包紮的傷口',1.2);}else if(['frag','flash','smoke'].includes(name))core.throwItem(p,name);else if(name.startsWith('slot'))core.switchWeapon(p,p.inventory[+name.slice(-1)-1]);else if(['weapon','next','previous'].includes(name)){const n=p.inventory.indexOf(p.active);core.switchWeapon(p,p.inventory[(n+(name==='previous'?2:1))%3]);}}
function mapBackground(canvas,full=false,player=null){const ctx=canvas.getContext('2d'),width=canvas.width,height=canvas.height;ctx.clearRect(0,0,width,height);ctx.fillStyle='#0c1b25';ctx.fillRect(0,0,width,height);const xs=D.floor.map(p=>p[0]),zs=D.floor.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minZ=Math.min(...zs),maxZ=Math.max(...zs);let scale=full?Math.min((width-30)/(maxX-minX),(height-30)/(maxZ-minZ)):5.2,ox=full?(width-(maxX-minX)*scale)/2-minX*scale:width/2-player.pos.x*scale,oz=full?(height-(maxZ-minZ)*scale)/2-minZ*scale:height/2-player.pos.z*scale;
 const polygon=(poly,fill,stroke)=>{ctx.beginPath();poly.forEach(([x,z],i)=>{if(i)ctx.lineTo(x*scale+ox,z*scale+oz);else ctx.moveTo(x*scale+ox,z*scale+oz);});ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.stroke();}};
 polygon(D.floor,'#152c39','#3e6175');for(const w of D.walls)polygon(w.outer,'#628195');for(const o of D.objects)if(o.outline)polygon(o.outline,o.kind==='machine'?'#315265':'#263f4d');
 if(core&&M?.bases?.length){for(const [i,p]of M.bases.entries()){ctx.fillStyle=teamColor(i);ctx.beginPath();ctx.arc(p.x*scale+ox,p.z*scale+oz,full?5:6,0,Math.PI*2);ctx.fill();}if(M.mode==='bomb')for(const [i,p]of M.sites.entries()){ctx.fillStyle='#f1c776';ctx.font='bold 14px sans-serif';ctx.fillText(i?'B':'A',p.x*scale+ox,p.z*scale+oz);}}
 if(player){for(const a of M.actors)if(a.hp>0){const visible=a.team===player.team||a.id===player.target||M.time-(a.lastSpotted||-100)<1;if(!visible)continue;ctx.fillStyle=a.human?'#fff':teamColor(a.team);ctx.beginPath();ctx.arc(a.pos.x*scale+ox,a.pos.z*scale+oz,a.human?4:3,0,Math.PI*2);ctx.fill();}ctx.save();ctx.translate(player.pos.x*scale+ox,player.pos.z*scale+oz);ctx.rotate(-player.facing);ctx.strokeStyle='#ffffff99';ctx.beginPath();ctx.moveTo(-10,-17);ctx.lineTo(0,0);ctx.lineTo(10,-17);ctx.stroke();ctx.restore();if(M.mode==='ctf')for(const f of M.flags){ctx.strokeStyle=teamColor(f.team);ctx.strokeRect(f.pos.x*scale+ox-4,f.pos.z*scale+oz-4,8,8);}}
 return ctx;
}

function updateLabels(){if(!camera||!M.player)return;camera.updateMatrixWorld(true);const p=M.player,labels=[];for(const a of M.actors)if(!a.human&&a.hp>0&&a.team===p.team&&a.pos.distanceTo(p.pos)<35&&S.clear(camera.position,core.eye(a))){const v=a.pos.clone().add(V(0,2,0)).project(camera);if(v.z<1&&Math.abs(v.x)<1&&Math.abs(v.y)<1)labels.push('<span class="nametag" style="left:'+((v.x+1)*innerWidth/2)+'px;top:'+((1-v.y)*innerHeight/2)+'px">▾ '+a.name+' · '+Math.ceil(a.hp)+'</span>');}const targets=M.mode==='bomb'?M.bomb.planted?[{pos:M.bomb.pos,name:'BOMB'}]:M.sites.map((pos,i)=>({pos,name:i?'B':'A'})):M.mode==='ctf'?M.flags.map(f=>({pos:f.pos,name:f.team===p.team?'BASE':'FLAG'})):[];for(const target of targets){const pos=target.pos.clone().add(V(0,1,0)),v=pos.project(camera);if(v.z<1){labels.push('<span class="objective-tag" style="left:'+clamp((v.x+1)*innerWidth/2,50,innerWidth-50)+'px;top:'+clamp((1-v.y)*innerHeight/2,140,innerHeight-120)+'px">'+target.name+'<br>'+Math.round(target.pos.distanceTo(p.pos))+'m</span>');}}$('worldLabels').innerHTML=labels.join('');}

function updateHUD(){if(!M||menuShown)return;const p=M.player,w=W[p.active],now=performance.now()/1000;$('blueScore').textContent=M.mode==='waves'?'W'+M.wave.number:M.scores[0];$('redScore').textContent=M.mode==='waves'?M.wave.queued+M.actors.filter(a=>!a.human&&a.hp>0).length:M.scores[1];$('nextWave').hidden=!(M.mode==='waves'&&M.phase==='warmup'&&!M.paused);$('timer').textContent=M.mode==='waves'&&M.phase==='warmup'?seconds(M.warmup):['practice','waves'].includes(M.mode)?seconds(M.time):M.mode==='bomb'&&M.bomb.planted?seconds(M.bomb.explodeAt-M.time):seconds(M.remaining);$('modeLabel').textContent=MODES[M.mode].tag+(MODES[M.mode].rounds?' / R'+M.round:'');$('zone').textContent=p.team===0?'BLUE':'RED';$('health').textContent=Math.ceil(p.hp);$('healthBar').style.width=clamp(p.hp,0,100)+'%';$('healthBar').style.background=p.hp<30?'#ff7668':'#d6e5dc';$('armor').textContent='ARMOR '+Math.ceil(p.armor)+' / H '+Math.ceil(p.helmet);$('stamina').textContent='STAMINA '+Math.floor(p.stamina);$('staminaBar').style.width=p.stamina+'%';$('movement').textContent=p.slide>0?'SLIDING':!p.grounded?'AIR':Math.hypot(p.vel.x,p.vel.z)>6?'SPRINT':p.crouch?'CROUCH':'READY';$('condition').textContent=[p.bleed>0?'流血中 · B 包紮':'',p.leg>0?'腿部受傷':''].filter(Boolean).join(' / ');$('ammo').textContent=p.active==='knife'?'—':p.ammo[p.active];$('reserve').textContent=p.active==='knife'?'':'/ '+p.reserve[p.active];$('weaponName').textContent=p.preparedThrow?({frag:'手榴彈',flash:'閃光彈',smoke:'煙霧彈'}[p.preparedThrow.type]+' / 準備投擲'):w.name+' · '+w.label+(p.reload>0?' / 換彈中':'');$('equipment').textContent='G '+p.frag+'　H '+p.flash+'　J '+p.smoke+'　│　K '+p.kills+' / D '+p.deaths;
 const objective=M.mode==='waves'?'第 '+M.wave.number+' 波 · 場上 '+M.actors.filter(a=>!a.human&&a.hp>0).length+' / 待入場 '+M.wave.queued+' · 已完成 '+M.wave.completed+' 波':M.mode==='bomb'?(M.bomb.planted?'炸彈已安裝 · '+(p.team===M.attackTeam?'守住炸彈':'前往拆除'):p.team===M.attackTeam?'進攻 A / B · '+(M.bomb.carrier===p.id?'你攜帶炸彈':'掩護攜彈隊友'):'防守 A / B · 阻止敵方安裝'):M.mode==='ctf'?'敵旗帶回基地 · 我方旗須在基地':M.mode==='ts'?'殲滅敵方全隊 · 每回合一次生命':M.mode==='practice'?'練習場 · 五名移動目標 · 暫停可返回主頁':'目標 50 擊殺 · '+M.teamSize+' vs '+M.teamSize;$('objective').textContent=(uiOnly?'3D 未啟動 · ':'')+objective;
 const progress=p.reload>0?1-p.reload/p.reloadTotal:p.bandage>0?1-p.bandage/p.bandageTotal:M.bomb?.worker===p.id?M.bomb.progress/(M.bomb.planted?5:3):0;$('actionProgress').hidden=progress<=0;$('actionProgress').firstElementChild.style.width=clamp(progress*100,0,100)+'%';
 let interaction=p.preparedThrow?({frag:'手榴彈',flash:'閃光彈',smoke:'煙霧彈'}[p.preparedThrow.type]+'已備妥 · '+(mobile?'放開按鈕投擲':'放開 '+{frag:'G',flash:'H',smoke:'J'}[p.preparedThrow.type]+' 投擲')):p.hp>0?core.interact(p,0):'';if(p.bandage>0)interaction='包紮中… '+p.bandage.toFixed(1)+'s';$('interaction').textContent=interaction;$('interaction').hidden=!interaction;$('useTouch').hidden=!interaction||p.bandage>0||!!p.preparedThrow;const selected=input?.state.throwType||'frag';$('throwTouch').innerHTML={frag:'手榴彈',flash:'閃光彈',smoke:'煙霧彈'}[selected]+'<small>'+p[selected]+' · 按住</small>';$('throwTouch').classList.toggle('active',!!p.preparedThrow);$('throwTouch').disabled=!p.preparedThrow&&(p[selected]<=0||M.phase!=='active'||p.bandage>0);$('throwSelectTouch').disabled=!!p.preparedThrow;$('fireTouch').disabled=$('aimTouch').disabled=!!p.preparedThrow;$('bandageTouch').disabled=!p.bleed&&!p.leg;$('reloadTouch').disabled=!!p.preparedThrow||p.reload>0||p.ammo[p.active]>=w.mag||p.active==='knife';for(const b of document.querySelectorAll('[data-throw]')){const type=b.dataset.throw;b.disabled=p[type]<=0;b.textContent={frag:'手榴彈',flash:'閃光彈',smoke:'煙霧彈'}[type]+' '+p[type];}
 $('crosshair').classList.toggle('ads',p.aim);$('scope').hidden=!(p.aim&&w.scope&&p.hp>0);$('crosshair').hidden=!$('scope').hidden||p.hp<=0;$('touch').hidden=!mobile||!allowed();$('death').hidden=p.hp>0||M.phase==='ended';$('deathText').textContent=MODES[M.mode].respawn?Math.max(0,Math.ceil(p.respawnAt-M.time))+' 秒後重生':'等待下一回合 · 自動觀戰存活隊友';
 if(M.phase==='warmup')toast(M.mode==='waves'?'第 '+M.wave.number+' 波準備　'+Math.ceil(M.warmup)+' 秒\n已補給 · '+(mobile?'可按下方按鈕開始':'Enter 提前開始'):'準備行動　'+Math.ceil(M.warmup),.2);if(now>toastEnd)$('toast').hidden=true;while(feed.length&&feed[0].until<now)feed.shift();$('killfeed').innerHTML=feed.map(e=>{const victim=M.actors.find(a=>a.id===e.actor),killer=M.actors.find(a=>a.id===e.by);return '<div class="feedline"><span style="color:'+teamColor(killer?.team??0)+'">'+e.killer+'</span>　'+(W[e.weapon]?.name||{frag:'爆炸',bleed:'流血',fall:'墜落'}[e.weapon]||e.weapon)+'　<span style="color:'+teamColor(victim?.team??1)+'">'+e.name+'</span></div>';}).join('');$('compass').textContent=['N','NW','W','SW','S','SE','E','NE'][Math.floor(((p.facing%(Math.PI*2)+Math.PI*2)%(Math.PI*2)+Math.PI/8)/(Math.PI/4))%8]+'　'+Math.round(((p.facing*180/Math.PI)%360+360)%360)+'°';$('fps').hidden=!settings.showFPS;$('fps').textContent=Math.round(fps)+' FPS  / '+(renderer?renderer.info.render.calls:0)+' DRAWS';if(!$('scorePanel').hidden&&M.phase!=='ended')renderScores();}
function updateFX(dt){for(let i=fx.length-1;i>=0;i--){const e=fx[i];e.life-=dt;if(e.life<=0){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();fx.splice(i,1);continue;}e.mesh.material.opacity=e.life/e.total;if(e.vel){e.vel.y-=6*dt;e.mesh.position.addScaledVector(e.vel,dt);}}
 for(const [id,g]of projectileModels)if(!M.projectiles.some(p=>p.id===id)){scene.remove(g);g.geometry.dispose();g.material.dispose();projectileModels.delete(id);}for(const p of M.projectiles){let g=projectileModels.get(p.id);if(!g){g=new T.Mesh(new T.SphereGeometry(.075,10,8),new T.MeshStandardMaterial({color:p.type==='frag'?0x56644a:p.type==='smoke'?0x82939a:0xc3c8ba,roughness:.7}));scene.add(g);projectileModels.set(p.id,g);}g.position.copy(p.pos);g.rotation.x+=dt*3;}
 for(const [id,g]of smokeModels)if(!M.smokes.some(s=>s.id===id)){scene.remove(g);g.traverse(o=>{if(o.isMesh){o.geometry.dispose();o.material.dispose();}});smokeModels.delete(id);}for(const s of M.smokes){let g=smokeModels.get(s.id);if(!g){g=new T.Group();for(let i=0;i<10;i++){const mesh=new T.Mesh(new T.SphereGeometry(1,12,8),new T.MeshBasicMaterial({color:0x89949b,transparent:true,opacity:.22,depthWrite:false}));mesh.position.set(Math.cos(i*2.4)*1.7,.4+(i%3)*.55,Math.sin(i*2.4)*1.7);mesh.scale.set(2.3,1.7,2.3);g.add(mesh);}g.position.copy(s.pos);scene.add(g);smokeModels.set(s.id,g);}const age=M.time-s.start,scale=Math.min(1,age/1.8),fade=Math.min(1,(s.end-M.time)/3);g.scale.setScalar(scale);g.rotation.y=age*.025;g.children.forEach(m=>m.material.opacity=.27*fade);}
 for(const [drop,g]of dropModels)if(!M.drops.includes(drop)){scene.remove(g);dropModels.delete(drop);}for(const d of M.drops){let g=dropModels.get(d);if(!g){g=visual.gun(d.id);g.rotation.z=Math.PI/2;g.position.copy(d.pos);g.position.y=.15;scene.add(g);dropModels.set(d,g);}}
 for(let i=0;i<flagModels.length;i++){const f=M.flags[i],g=flagModels[i];g.position.copy(f.pos);g.position.y=f.carrier!==null?.7:0;g.rotation.y=M.time*.4;}
}
function updateCamera(dt,delta){const p=M.player;let target=p;if(p.hp<=0){if(!deathTarget||deathTarget.hp<=0)deathTarget=M.actors.find(a=>a.team===p.team&&a.hp>0);if(deathTarget)target=deathTarget;}const eye=core.eye(target);const bob=settings.motion&&target.hp>0&&target.grounded?Math.sin(M.time*12)*Math.min(.017,Math.hypot(target.vel.x,target.vel.z)*.0025):0;camera.position.lerp(eye,1-Math.exp(-dt*30));camera.position.y+=bob;camera.rotation.order='YXZ';camera.rotation.set(target.pitch,target.facing,(p.slide>0?.045:0));const w=W[p.active],desired=p.aim?(w.scope?26:settings.fov*.78):settings.fov;camera.fov+=(desired-camera.fov)*(1-Math.exp(-dt*12));camera.updateProjectionMatrix();visual.updateView(p,dt,M.time,settings,delta);}
function frame(now){requestAnimationFrame(frame);const dt=Math.min(.1,Math.max(0,(now-last)/1000));last=now;previewClock+=dt;fpsClock+=dt;frameCount++;if(fpsClock>=.5){fps=frameCount/fpsClock;frameCount=0;fpsClock=0;}
 if(!booted)return;if(!menuShown){let sample=allowed()?input.read():{};if(!M.paused&&M.phase!=='ended'){accumulator+=dt;let count=0;while(accumulator>=1/60&&count++<6){core.tick(1/60,sample);sample.jump=false;sample.firePressed=false;accumulator-=1/60;}if(count>0)input.consumed();}if(scene){for(const [id,model]of actorModels)if(!M.actors.some(a=>a.id===id)){model.remove();actorModels.delete(id);}for(const a of M.actors){if(!a.human&&!actorModels.has(a.id))actorModels.set(a.id,visual.actor(a.team));const model=actorModels.get(a.id);if(model)model.update(a,M.paused?0:dt,M.time);}for(const d of F.doors){if(d.type==='sliding'){d.group.position.set(d.hinge[0]+d.slide[0]*d.t,0,d.hinge[1]+d.slide[1]*d.t);}else d.group.rotation.y=-(d.angle+d.swing*d.t);}if(!M.paused)updateFX(dt);updateCamera(dt,sample);}hudTimer+=dt;radarTimer+=dt;if(hudTimer>.08){updateHUD();hudTimer=0;}if(radarTimer>.2){updateLabels();mapBackground($('radar'),false,M.player);radarTimer=0;}
 const wall=now/1000;$('hitmarker').style.opacity=wall<hitEnd?'1':'0';$('damage').style.opacity=String(Math.max(M.player.hp<25?.15:0,Math.max(0,hurtEnd-wall)*1.3));$('direction').style.opacity=wall<hurtEnd?'1':'0';$('flash').style.opacity=String(clamp(M.player.flashTime*.55,0,.96));}
 else if(scene){const center=core.component[Math.floor(core.component.length*.5)]||V(D.spawn[0],0,D.spawn[1]);camera.position.set(center.x+Math.cos(previewClock*.06)*13,14,center.z+Math.sin(previewClock*.06)*13);camera.lookAt(center.x,0,center.z);camera.fov=63;camera.updateProjectionMatrix();F.ceiling.visible=false;}
 if(renderer){renderer.info.reset();if(!menuShown)F.ceiling.visible=true;renderer.autoClear=true;renderer.render(scene,camera);if(!menuShown&&M.player.hp>0&&!uiOnly){renderer.autoClear=false;renderer.clearDepth();renderer.render(visual.viewScene,visual.viewCamera);renderer.autoClear=true;}}
}
function boot(){try{if(!uiOnly)renderer=new T.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});scene=renderer?new T.Scene():null;if(scene){scene.background=new T.Color(0x111c26);scene.fog=new T.FogExp2(0x536470,.006);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.13;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.info.autoReset=false;$('world').append(renderer.domElement);camera=new T.PerspectiveCamera(settings.fov,innerWidth/innerHeight,.035,180);scene.add(new T.HemisphereLight(0xdeebf5,0x526574,2.2));sun=new T.DirectionalLight(0xffecd2,2.5);sun.position.set(D.spawn[0]+18,35,D.spawn[1]+14);sun.target.position.set(D.spawn[0],0,D.spawn[1]);scene.add(sun);scene.add(sun.target);sun.castShadow=true;Object.assign(sun.shadow.camera,{left:-35,right:35,top:35,bottom:-35,near:1,far:95});sun.shadow.bias=-.0005;sun.shadow.normalBias=.035;F=makeFactory(T,D);F.avatar.visible=false;F.cad.visible=false;scene.add(F.root);}else{F={doors:D.doors.map(d=>({...d,t:0,target:0}))};$('world').style.background='radial-gradient(ellipse at 72% 40%,#385668,#12222e 70%)';}
 S=makeStrikeSpace(D,F);core=StrikeCore.createMatch({space:S,data:D,doors:F.doors,emit:onEvent});M=core.M;core.prepareMap();if(scene)visual=makeStrikeVisuals(T,scene,camera,F,D);const canvas=renderer?.domElement||$('world');input=makeStrikeInput({canvas,mobile,allowed,look(dx,dy,aim){if(!M.player)return;const sensitivity=settings.sensitivity/100*.0022*(aim?settings.ads/100:1)*(mobile?1.3:1);M.player.facing-=dx*sensitivity;M.player.pitch=clamp(M.player.pitch-dy*sensitivity,-1.45,1.45);},action,map:mapOpen,unlock:audio.unlock,lock,pause,scores:(on)=>scores(on,true),blur(){if(!menuShown&&!M.paused&&M.phase!=='ended')pause();}});applySettings();mapBackground($('briefMap'),true);booted=true;$('loading').hidden=true;last=performance.now();requestAnimationFrame(frame);
 document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&!mobile&&!menuShown&&!M.paused&&M.phase!=='ended'&&!pauseLock&&$('scorePanel').hidden)pause();});addEventListener('resize',()=>{if(renderer){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}});
 if(location.search.includes('autostart=1'))deploy(location.search.includes('practice=1'));
 }catch(error){console.error(error);$('loading').hidden=true;$('deploy').disabled=true;$('practice').disabled=true;const p=document.createElement('p');p.style.cssText='padding:14px;color:#ffb39c;border:1px solid #925c46;margin:12px 0;background:#281b18';p.textContent='無法啟動 3D：'+error.message+'。請啟用瀏覽器硬體加速，或使用支援 WebGL 的 Chrome、Edge、Safari。';$('menu').prepend(p);mapBackground($('briefMap'),true);}}
applySettings();requestAnimationFrame(()=>setTimeout(boot,30));
})();
