function makeStrikeInput(api){
 const $=id=>document.getElementById(id),keys=new Set(),pointers=new Map(),state={x:0,z:0,aim:false,crouch:false,fire:false,firePressed:false,jump:false,use:false,sprint:false,walk:false,dx:0,dy:0};let moveId=null,lookId=null,lastX=0,lastY=0,mouseFire=false,mouseAim=false;
 const allowed=()=>api.allowed();
 function reset(){keys.clear();pointers.clear();moveId=lookId=null;mouseFire=mouseAim=false;Object.assign(state,{x:0,z:0,aim:false,crouch:false,fire:false,firePressed:false,jump:false,use:false,sprint:false,walk:false,dx:0,dy:0});$('knob').style.transform='';$('throwTray').hidden=true;for(const b of document.querySelectorAll('.touchbutton'))b.classList.remove('active');}
 function look(dx,dy){if(!allowed())return;state.dx+=dx;state.dy+=dy;api.look(dx,dy,state.aim);}
 document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(['Tab','Space','AltLeft','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){api.pause();return;}if(e.code==='Tab'){api.scores(true);return;}if(!allowed())return;keys.add(e.code);if(e.repeat)return;if(e.code==='Space')state.jump=true;if(e.code==='KeyM')api.map();if(e.code==='KeyR')api.action('reload');if(e.code==='KeyB')api.action('bandage');if(e.code==='KeyG')api.action('frag');if(e.code==='KeyH')api.action('flash');if(e.code==='KeyJ')api.action('smoke');if(/^Digit[123]$/.test(e.code))api.action('slot'+e.code.slice(-1));});
 document.addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Tab'){e.preventDefault();api.scores(false);}});
 document.addEventListener('mousemove',e=>{if(document.pointerLockElement===api.canvas)look(e.movementX,e.movementY);});
 api.canvas.addEventListener('mousedown',e=>{if(!allowed()||api.mobile)return;api.unlock();if(document.pointerLockElement!==api.canvas){api.lock();return;}if(e.button===0){mouseFire=true;state.firePressed=true;}if(e.button===2)mouseAim=true;});document.addEventListener('mouseup',e=>{if(e.button===0)mouseFire=false;if(e.button===2)mouseAim=false;});api.canvas.addEventListener('contextmenu',e=>e.preventDefault());api.canvas.addEventListener('wheel',e=>{if(allowed()){e.preventDefault();api.action(e.deltaY>0?'next':'previous');}},{passive:false});
 function capture(el,e){e.preventDefault();try{el.setPointerCapture(e.pointerId);}catch(err){}}
 const stick=$('stick');function move(e){const r=stick.getBoundingClientRect(),radius=r.width*.34,dx=(e.clientX-r.left-r.width/2)/radius,dz=-(e.clientY-r.top-r.height/2)/radius,len=Math.hypot(dx,dz),amount=Math.max(0,Math.min(1,(len-.13)/.87));state.x=len?dx/len*amount:0;state.z=len?dz/len*amount:0;state.sprint=state.z>.83&&Math.abs(state.x)<.55;$('knob').style.transform='translate('+state.x*radius+'px,'+-state.z*radius+'px)';}
 stick.addEventListener('pointerdown',e=>{if(!allowed()||moveId!==null)return;moveId=e.pointerId;capture(stick,e);move(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===moveId&&allowed())move(e);});for(const name of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(name,e=>{if(e.pointerId===moveId){moveId=null;state.x=state.z=0;state.sprint=false;$('knob').style.transform='';}});
 api.canvas.addEventListener('pointerdown',e=>{if(!api.mobile||!allowed()||lookId!==null||e.clientX<innerWidth*.3)return;lookId=e.pointerId;lastX=e.clientX;lastY=e.clientY;capture(api.canvas,e);});api.canvas.addEventListener('pointermove',e=>{if(e.pointerId===lookId&&allowed()){look(e.clientX-lastX,e.clientY-lastY);lastX=e.clientX;lastY=e.clientY;}});for(const name of ['pointerup','pointercancel','lostpointercapture'])api.canvas.addEventListener(name,e=>{if(e.pointerId===lookId)lookId=null;});
 function sync(){state.fire=mouseFire||[...pointers.values()].some(p=>p.action==='fire'||p.action==='fireLeft');state.use=keys.has('KeyF')||[...pointers.values()].some(p=>p.action==='use');for(const b of document.querySelectorAll('.touchbutton')){const action=b.dataset.action;b.classList.toggle('active',action==='aim'?state.aim:action==='crouch'?state.crouch:[...pointers.values()].some(p=>p.action===action));}}
 for(const b of document.querySelectorAll('#touch button[data-action]')){b.addEventListener('pointerdown',e=>{if(!allowed()||b.disabled)return;api.unlock();capture(b,e);const action=b.dataset.action;pointers.set(e.pointerId,{action,x:e.clientX,y:e.clientY});if(action==='fire'||action==='fireLeft')state.firePressed=true;else if(action==='aim')state.aim=!state.aim;else if(action==='crouch')state.crouch=!state.crouch;else if(action==='jump')state.jump=true;else if(action==='throws')$('throwTray').hidden=!$('throwTray').hidden;else if(action!=='use')api.action(action);sync();});b.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(p&&p.action==='fire'&&allowed()){look(e.clientX-p.x,e.clientY-p.y);p.x=e.clientX;p.y=e.clientY;}});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>{pointers.delete(e.pointerId);sync();});}
 for(const b of document.querySelectorAll('[data-throw]'))b.onclick=()=>{if(allowed())api.action(b.dataset.throw);$('throwTray').hidden=true;};
 addEventListener('blur',()=>{reset();api.blur();});document.addEventListener('visibilitychange',()=>{if(document.hidden){reset();api.blur();}});addEventListener('resize',reset);addEventListener('orientationchange',reset);
 return {reset,state,read(){if(!api.mobile){state.x=Number(keys.has('KeyD'))-Number(keys.has('KeyA'));state.z=Number(keys.has('KeyW'))-Number(keys.has('KeyS'));state.sprint=keys.has('ShiftLeft')||keys.has('ShiftRight');state.walk=keys.has('AltLeft');state.crouch=keys.has('ControlLeft')||keys.has('ControlRight')||keys.has('KeyC');state.aim=mouseAim;}sync();return {...state};},consumed(){state.firePressed=false;state.jump=false;state.dx=state.dy=0;}};
}
