'use strict';
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
class Element{constructor(id,action){this.id=id;this.dataset=action?{action}:{};this.handlers={};this.style={};this.hidden=false;this.disabled=false;this.classList={add(){},remove(){},toggle(){}};this.tagName='DIV';}addEventListener(name,fn){(this.handlers[name]||=[]).push(fn);}send(name,data={}){for(const fn of this.handlers[name]||[])fn({target:this,preventDefault(){},...data});}setPointerCapture(){}getBoundingClientRect(){return {left:0,top:0,width:130,height:130};}}
const makeInput=vm.runInThisContext(fs.readFileSync(__dirname+'/input.js','utf8')+';makeStrikeInput');let count=0;
function setup(mobile=true){const ids=['knob','throwTray','stick'],els=Object.fromEntries(ids.map(id=>[id,new Element(id)])),actions=['fire','fireLeft','aim','crouch','jump','use','reload','weapon','throws'],buttons=actions.map(a=>new Element(a,a)),doc=new Element('document'),win=new Element('window'),canvas=new Element('canvas');doc.getElementById=id=>els[id];doc.querySelectorAll=s=>s==='[data-throw]'?[]:buttons;global.document=doc;global.addEventListener=win.addEventListener.bind(win);global.innerWidth=844;let enabled=true,looks=[],commands=[],blur=0,locked=0;const input=makeInput({mobile,canvas,allowed:()=>enabled,look:(...v)=>looks.push(v),action:x=>commands.push(x),unlock(){},lock(){locked++},pause(){},map(){commands.push('map')},scores(){},blur(){blur++}});return {input,els,buttons:Object.fromEntries(buttons.map(b=>[b.id,b])),doc,win,canvas,looks,commands,disable:()=>enabled=false,get blur(){return blur},get locked(){return locked}};}
function test(name,fn){fn();console.log('PASS',name);count++;}
const down=(el,id,x=600,y=200)=>el.send('pointerdown',{pointerId:id,clientX:x,clientY:y}),up=(el,id)=>el.send('pointerup',{pointerId:id});
test('move, look, fire and aim retain independent pointer ownership',()=>{const s=setup();down(s.els.stick,1,65,10);down(s.canvas,2);down(s.buttons.fire,3);down(s.buttons.aim,4);s.canvas.send('pointermove',{pointerId:2,clientX:620,clientY:210});s.buttons.fire.send('pointermove',{pointerId:3,clientX:610,clientY:195});const r=s.input.read();assert(r.z>.9&&r.sprint&&r.fire&&r.aim);assert.equal(s.looks.length,2);up(s.buttons.aim,4);assert(s.input.read().fire);up(s.buttons.fire,3);assert(!s.input.read().fire);assert(s.input.read().z>.9);});
test('right fire release does not cancel left fire',()=>{const s=setup();down(s.buttons.fire,1);down(s.buttons.fireLeft,2);up(s.buttons.fire,1);assert(s.input.read().fire);s.buttons.fireLeft.send('pointercancel',{pointerId:2});assert(!s.input.read().fire);});
test('quick tap preserves one press until simulation consumes it',()=>{const s=setup();down(s.buttons.fire,1);up(s.buttons.fire,1);assert(!s.input.read().fire&&s.input.read().firePressed);s.input.consumed();assert(!s.input.read().firePressed);});
test('jump is one edge per press and crouch is a toggle',()=>{const s=setup();down(s.buttons.jump,1);assert(s.input.read().jump);s.input.consumed();assert(!s.input.read().jump);down(s.buttons.crouch,2);up(s.buttons.crouch,2);assert(s.input.read().crouch);down(s.buttons.crouch,2);assert(!s.input.read().crouch);});
test('pointer cancel and lost capture stop joystick and fire',()=>{const s=setup();down(s.els.stick,1,65,0);down(s.buttons.fire,2);s.els.stick.send('lostpointercapture',{pointerId:1});s.buttons.fire.send('pointercancel',{pointerId:2});assert.equal(s.input.read().z,0);assert(!s.input.read().fire);});
test('blur, rotation and resize clear all input and toggles',()=>{for(const name of ['blur','orientationchange','resize']){const s=setup();down(s.els.stick,1,65,0);down(s.buttons.fire,2);down(s.buttons.aim,3);s.win.send(name);const r=s.input.read();assert(!r.fire&&!r.aim&&!r.sprint&&!r.use&&r.z===0);if(name==='blur')assert.equal(s.blur,1);}});
test('desktop pointer lock gates shooting and input reset releases keys',()=>{const s=setup(false);s.canvas.send('mousedown',{button:0});assert.equal(s.locked,1);assert(!s.input.read().fire);s.doc.pointerLockElement=s.canvas;s.canvas.send('mousedown',{button:0});s.doc.send('keydown',{code:'KeyW'});s.doc.send('keydown',{code:'ShiftLeft'});assert(s.input.read().fire&&s.input.read().z===1&&s.input.read().sprint);s.doc.send('mouseup',{button:0});assert(s.input.read().firePressed&&!s.input.read().fire);s.input.reset();assert.equal(s.input.read().z,0);});
test('paused gameplay ignores touch actions and camera gestures',()=>{const s=setup();s.disable();down(s.buttons.reload,1);down(s.canvas,2);s.canvas.send('pointermove',{pointerId:2,clientX:630,clientY:210});assert.equal(s.commands.length,0);assert.equal(s.looks.length,0);});
console.log('INPUT RESULT',count,'tests passed');
