/* Original procedural tactical assets and batched factory rendering. */
function makeStrikeVisuals(T,scene,camera,F,D){
 const models=makeGameModels(T),box=new T.BoxGeometry(1,1,1),sphere=new T.SphereGeometry(1,12,8),cylinder=new T.CylinderGeometry(1,1,1,12),knifeTip=new T.ConeGeometry(.027,.09,3),materials=new Map();
 function material(color,metal=.1){const key=color+':'+metal;if(!materials.has(key))materials.set(key,new T.MeshStandardMaterial({color,metalness:metal,roughness:metal>.5?.38:.8}));return materials.get(key);}
 function part(parent,geo,color,p,s,metal=.1){const m=new T.Mesh(geo,material(color,metal));m.position.set(...p);m.scale.set(...s);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function cube(g,c,x,y,z,w,h,d,metal){return part(g,box,c,[x,y,z],[w,h,d],metal);}
 function ell(g,c,x,y,z,w,h,d){return part(g,sphere,c,[x,y,z],[w,h,d]);}
 function tube(g,c,x,y,z,r,h){const m=part(g,cylinder,c,[x,y,z],[r,h,r],.6);m.rotation.x=Math.PI/2;return m;}
 function combine(group,shallow=false){group.updateMatrixWorld(true);const buckets=new Map(),remove=[];group.traverse(o=>{if(o.isMesh&&!o.isInstancedMesh&&!Array.isArray(o.material)&&(!shallow||o.parent===group)){const key=o.material.uuid;if(!buckets.has(key))buckets.set(key,{mat:o.material,items:[]});buckets.get(key).items.push(o);remove.push(o);}});const inv=new T.Matrix4().copy(group.matrixWorld).invert();for(const {mat,items} of buckets.values()){const positions=[],normals=[],uvs=[];for(const m of items){const g=m.geometry.index?m.geometry.toNonIndexed():m.geometry.clone();g.applyMatrix4(new T.Matrix4().multiplyMatrices(inv,m.matrixWorld));positions.push(...g.attributes.position.array);normals.push(...g.attributes.normal.array);if(g.attributes.uv)uvs.push(...g.attributes.uv.array);else for(let i=0;i<g.attributes.position.count;i++)uvs.push(0,0);g.dispose();}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(positions,3));g.setAttribute('normal',new T.Float32BufferAttribute(normals,3));g.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));g.computeBoundingSphere();const merged=new T.Mesh(g,mat);merged.userData.strikeMerged=true;merged.castShadow=true;merged.receiveShadow=true;group.add(merged);}for(const o of remove)o.parent.remove(o);}
 // Frames are static. Door leaves remain independently operable.
 const frames=new T.Group();F.root.add(frames);for(const d of F.doors){frames.attach(d.frame);combine(d.group);}combine(frames);
 const walls=new T.Group();F.root.add(walls);for(const w of F.wallMeshes)walls.attach(w);combine(walls);
 F.ceiling.traverse(o=>{o.castShadow=false;});F.mats.wall.color.setHex(0x9ba5ab);F.mats.floor.color.setHex(0xaebbc0);F.mats.blue.color.setHex(0x728597);F.mats.teal.color.setHex(0x416771);
 F.mats.wall.roughness=.91;F.mats.floor.roughness=.42;F.mats.floor.metalness=.18;
 const markerMaterial=new T.MeshBasicMaterial({color:0xe4b86c,transparent:true,opacity:.75,side:T.DoubleSide,depthWrite:false});
 function floorRing(pos,color,r=1.4){const m=new T.Mesh(new T.RingGeometry(r-.055,r,48),new T.MeshBasicMaterial({color,side:T.DoubleSide,transparent:true,opacity:.8,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.copy(pos);m.position.y=.015;scene.add(m);return m;}
 function sign(text,color,w=2,h=.48){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#0c1b25';ctx.fillRect(0,0,512,128);ctx.strokeStyle=color;ctx.lineWidth=7;ctx.strokeRect(5,5,502,118);ctx.fillStyle=color;ctx.font='bold 46px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,64);const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;const m=new T.Mesh(new T.PlaneGeometry(w,h),new T.MeshBasicMaterial({map,side:T.DoubleSide}));return m;}
 // Keep factory fixtures while adding legible real-scale zone signs.
 for(const [i,door]of F.doors.entries())if(i%8===0){const g=sign('3F / '+String(i+1).padStart(2,'0'),'#c6d7df',1.1,.27);g.position.set(door.hinge[0]+Math.cos(door.angle)*door.r/2,2.42,door.hinge[1]+Math.sin(door.angle)*door.r/2);g.rotation.y=-door.angle;scene.add(g);}
 const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=64;const sh=shadowCanvas.getContext('2d'),grad=sh.createRadialGradient(32,32,3,32,32,32);grad.addColorStop(0,'rgba(0,0,0,.55)');grad.addColorStop(1,'rgba(0,0,0,0)');sh.fillStyle=grad;sh.fillRect(0,0,64,64);const shadowTex=new T.CanvasTexture(shadowCanvas);
 function rawGun(id){const spec=StrikeCore.WEAPONS[id];if(id==='knife'){const g=new T.Group();cube(g,0x242f35,0,-.04,.015,.04,.05,.15);cube(g,0xabbac3,0,-.035,-.16,.045,.012,.23,.9);const tip=part(g,knifeTip,0xbbc8ce,[0,-.035,-.31],[1,1,1],.8);tip.rotation.x=-Math.PI/2;g.userData.length=.35;return g;}const g=models.gun(spec.model);g.userData.strikeId=id;g.traverse(o=>{o.castShadow=true;if(['buttstock','handguard'].includes(o.name))o.material=material({rifle:0x536455,carbine:0x9e9476,smg:0x495a66,shotgun:0x806749,sniper:0x51677a,dmr:0x69766f,lmg:0x475746}[id]||0x536455);});if(id==='carbine'){g.scale.z=.84;cube(g,0x9e9476,.044,.01,-.30,.018,.072,.19);}if(id==='lmg'){const mag=g.userData.magazine;mag.clear();cube(mag,0x34473d,0,-.09,0,.15,.21,.12);g.scale.z=1.06;}if(id==='dmr'){g.scale.z=.88;cube(g,0x69766f,.043,.012,-.3,.018,.075,.24);const mag=g.userData.magazine;cube(mag,0x626c67,0,-.065,0,.062,.12,.082);}if(id==='sniper'){cube(g,0x51677a,.043,.005,-.4,.016,.063,.21);for(const side of [-1,1])tube(g,0x76818a,side*.064,-.035,-.58,.01,.24);}if(['rifle','carbine','smg','lmg'].includes(id)){cube(g,0x26323c,0,.10,-.1,.048,.035,.12);cube(g,0x2a343a,0,.145,-.1,.062,.07,.025);cube(g,0x27343b,0,.145,-.18,.065,.07,.02);const lens=cube(g,0x426d76,0,.147,-.188,.046,.048,.002,.6);lens.material=new T.MeshBasicMaterial({color:0x81c2d2,transparent:true,opacity:.16,depthWrite:false});cube(g,0x242e31,.05,-.025,-.27,.021,.13,.026);for(let k=0;k<8;k++)cube(g,0x38454f,0,.070,-.20-k*.021,.085,.009,.009,.8);tube(g,0x444f55,.06,-.015,-.32,.016,.11);}
  return g;
 }
 const gunTemplates=new Map();
 function gun(id){if(!gunTemplates.has(id)){const template=rawGun(id);if(template.userData.magazine)combine(template.userData.magazine,true);combine(template,true);template.traverse(o=>{if(o.userData.strikeMerged)o.userData.strikeShared=true;});gunTemplates.set(id,template);}const original=gunTemplates.get(id),copy=original.clone();copy.userData={...original.userData,magazine:copy.getObjectByName('magazine')};return copy;}
 function actor(team){const a=models.character('A1'),g=a.group,cloth=team===0?0x3b667b:0x885449,armor=team===0?0x273946:0x463632;const removed=[],teamMaterials=new Map();
  g.traverse(o=>{if(o.isMesh){const original=o.material.color.getHex();if(!teamMaterials.has(o.material.uuid)){const m=o.material.clone();if(original===0xe3e6e1)m.color.setHex(cloth);teamMaterials.set(o.material.uuid,m);}o.material=teamMaterials.get(o.material.uuid);if(['mask','face_opening','hood_crown'].includes(o.name)||o.name?.startsWith('mask_'))removed.push(o);o.castShadow=true;} });for(const m of removed)m.parent.remove(m);
  ell(g,0x272f30,0,1.56,-.01,.154,.19,.157);ell(g,team===0?0x364e5b:0x50453d,0,1.67,.014,.173,.12,.167);cube(g,0x71868a,0,1.61,-.158,.25,.068,.032,.6);cube(g,0x252d2c,0,1.48,-.146,.15,.084,.037);cube(g,armor,0,1.08,-.157,.37,.39,.09);cube(g,armor,0,1.1,.15,.32,.39,.11);
  for(const x of [-.12,0,.12]){cube(g,0x394039,x,1.0,-.222,.084,.14,.07);cube(g,0x646c5e,x,1.08,-.221,.08,.02,.075);}cube(g,team===0?0x65bcdc:0xe88773,0,1.23,-.214,.12,.048,.011);
  for(const side of [-1,1]){cube(a.legs[side===-1?0:1],0x283334,0,-.38,-.078,.115,.13,.065);tube(g,0x272e2e,side*.20,1.0,-.16,.031,.10);}const sh=new T.Mesh(new T.PlaneGeometry(1.2,1.2),new T.MeshBasicMaterial({map:shadowTex,transparent:true,depthWrite:false,opacity:.65}));sh.rotation.x=-Math.PI/2;scene.add(sh);for(const leg of a.legs)combine(leg,true);for(const arm of a.arms)combine(arm,true);combine(g,true);scene.add(g);
  return {a,g,shadow:sh,weaponId:null,update(actor,dt,time){if(this.weaponId!==actor.active){const weapon=gun(actor.active);a.setGun(StrikeCore.WEAPONS[actor.active].model==='knife'?'pistol':StrikeCore.WEAPONS[actor.active].model);a.weapon.clear();for(const child of [...weapon.children])a.weapon.add(child);a.weapon.userData=weapon.userData;this.weaponId=actor.active;}g.position.copy(actor.pos);g.rotation.y=actor.facing;if(actor.hp<=0){g.rotation.z=Math.min(Math.PI/2,(time-(this.deadAt||time))*.9);if(!this.deadAt)this.deadAt=time;g.position.y=.1;g.scale.y=.6;}else{this.deadAt=0;g.rotation.z=0;g.scale.y=actor.crouch||actor.slide>0?.71:1;const speed=Math.hypot(actor.vel.x,actor.vel.z);a.legs.forEach((l,i)=>l.rotation.x=Math.sin(time*11+i*Math.PI)*Math.min(.65,speed*.12));a.mount.rotation.x=actor.pitch;a.poseGun(true,actor.reload>0&&actor.active!=='knife');}sh.position.copy(actor.pos);sh.position.y=.018;sh.visible=actor.pos.y<2;sh.material.opacity=.65/(1+actor.pos.y);},remove(){scene.remove(g);scene.remove(sh);g.traverse(o=>{if(o.userData.strikeMerged&&!o.userData.strikeShared)o.geometry.dispose();});sh.geometry.dispose();for(const material of teamMaterials.values())material.dispose();sh.material.dispose();}};
 }
 const firstPerson=makeStrikeViewModel(T,camera,gun);
 const markers=[];function clearMarkers(){for(const m of markers){scene.remove(m);m.geometry.dispose();m.material.map?.dispose();m.material.dispose();}markers.length=0;}
 function addObjectives(M){clearMarkers();if(M.mode==='waves')return;for(let t=0;t<2;t++){const color=t===0?0x57c6fa:0xef7e69;const base=M.mode==='ctf'?M.flagBases[t]:M.bases[t],ring=floorRing(base,color,2.4);markers.push(ring);const g=sign(t===0?'BLUE / BASE':'RED / BASE',t===0?'#72cefb':'#ffa08a',2.4,.48);g.position.copy(base);g.position.y=2.5;scene.add(g);markers.push(g);}if(M.mode==='bomb')for(let i=0;i<2;i++){const r=floorRing(M.sites[i],0xf5c66e,2.3);markers.push(r);const label=sign(i===0?'A / PLANT':'B / PLANT','#f5c66e',1.7,.44);label.position.copy(M.sites[i]);label.position.y=2.2;scene.add(label);markers.push(label);}}
 return {actor,gun,part,cube,ell,tube,sign,floorRing,materials,...firstPerson,addObjectives};
}
