(()=>{'use strict';
const $=id=>document.getElementById(id),D=window.FLOOR_DATA;
const mobile=!!(window.matchMedia?.('(pointer: coarse)').matches||/Android|iPhone|iPad|iPod/i.test(window.navigator?.userAgent||''));
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:!mobile,powerPreference:'high-performance'});}catch(e){$('loading').textContent='無法啟動 WebGL，請用啟用硬體加速的 Chrome／Edge。';return;}
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?1:1.25));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.88;$('canvas').appendChild(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color(0x1a2835);scene.fog=new THREE.Fog(0x243746,28,80);scene.add(new THREE.HemisphereLight(0xcce5f1,0x464542,1.6));const sun=new THREE.DirectionalLight(0xffd8a4,1.5);sun.position.set(20,50,10);scene.add(sun);
const F=makeFactory(THREE,D);scene.add(F.root);F.ceiling.visible=true;F.cad.visible=false;F.avatar.visible=false;const S=makeSpace(D,F),camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.05,130),clock=new THREE.Clock();
const look=makeArenaLook(THREE,scene,F,D);
const boxGeo=new THREE.BoxGeometry(1,1,1),sphereGeo=new THREE.SphereGeometry(1,9,6),cylGeo=new THREE.CylinderGeometry(1,1,1,10),mats={};
function mat(c){if(!mats[c])mats[c]=new THREE.MeshStandardMaterial({color:c,roughness:.72,metalness:.12});return mats[c];}
function mesh(parent,type,color,x,y,z,w,h,d){const o=new THREE.Mesh(type==='sphere'?sphereGeo:type==='cyl'?cylGeo:boxGeo,mat(color));o.position.set(x,y,z);o.scale.set(w,h,d);parent.add(o);return o;}
const models=makeGameModels(THREE);
function gunModel(id){return models.gun(id);}
let enemyModelIndex=0;
function actor(enemy=false){const a=models.character(enemy?['A1','B1','C1'][enemyModelIndex++%3]:'trump');scene.add(a.group);return a;}
const avatar=actor(false),P={pos:new THREE.Vector3(...[D.spawn[0],0,D.spawn[1]]),hp:100,armor:0,vy:0,fuel:100,status:{},flash:0};
let xp={},saveOK=true;try{const v=JSON.parse(localStorage.getItem('factory-shooter-xp-v1')||'{}');for(const id in GUNS)xp[id]=Number.isFinite(v[id])?clamp(v[id],0,1e8):0;}catch(e){saveOK=false;}
function save(){try{localStorage.setItem('factory-shooter-xp-v1',JSON.stringify(xp));saveOK=true;}catch(e){saveOK=false;}$('saveStatus').textContent=saveOK?'武器經驗已保存在此瀏覽器':'無法自動保存，請匯出武器進度';}
save();let practice=false,creeperSpawned=false;let mode='menu',previousMode='buy',wave=0,remaining=0,kills=0,money=CFG.startMoney,difficulty=1.3,phaseTime=0,gameTime=0,yaw=Math.PI,pitch=-.12,aim=false,fireHeld=false,reloadEnd=0,lastShot=0,active='pistol',inventory={side:'pistol',main:null},ammo={},grenades=2,flashes=2,hook=null,hookCD=0,hookLatch=false,jumpLatch=false,jet=false,crouched=false,grounded=true,noticeEnd=0,step=0,fireFlash=0,hurtFlash=0,damageDirectionEnd=0,flowTimer=0,spawnTimer=0,lastFPS=30,nearestDrop=null,nearestDoor=null,shopOpen=false,pendingXP=false,saveTimer=0;
const keys=new Set(),enemies=[],barrels=[],drops=[],projectiles=[],particles=[],decals=[],tracers=[];const difficultyNames={'1':'簡單','1.3':'普通','1.65':'困難'};
let reviveUntil=0,paidUpgrades={};
const blessings=makeBlessings({canChoose:()=>mode==='buy'&&wave>1,grenades:n=>grenades+=n,armorMax:()=>armorMax(),armorFill:n=>P.armor=Math.min(armorMax(),P.armor+n),resize:()=>resizePlayer(),changed:text=>{notify(text,4);renderShop();updateHUD();}});
const py=n=>n*blessings.B.height;
function armorMax(){return Math.round(CFG.armorMax*blessings.B.armor);}
function resizePlayer(){const h=py(1.72);P.pos.y=Math.min(P.pos.y,CFG.floorHeight-h-.02);if(S.blocked(P.pos.x,P.pos.y,P.pos.z,.22,h)){const candidates=S.candidates(P.pos.clone().setY(0),0,100).filter(p=>!S.blocked(p.x,0,p.z,.22,h)).sort((a,b)=>a.distanceToSquared(P.pos)-b.distanceToSquared(P.pos));if(candidates.length)P.pos.copy(candidates[0]);}P.vy=0;}
const actions=makeArenaActions(THREE,{scene,avatar,player:P,space:S,mode:()=>mode,shop:()=>shopOpen,time:()=>gameTime,yaw:()=>yaw,keys:()=>keys,enemies:()=>enemies,hurt:(e,n)=>hurtEnemy(e,n*blessings.B.attack,true,null),move:(x,z)=>moveActor(P,x,0,z,py(crouched?1.12:1.72)),cancelGun:()=>{fireHeld=false;aim=false;reloadEnd=0;},endHook,sound,notify,height:()=>blessings.B.height,reach:()=>blessings.B.reach,structureHit:(h,n)=>destruction.hit(h,n*blessings.B.attack),agvMelee:(o,dir,range,n)=>{const a=tactics.getAGV();if(a&&a.hp>0&&a.pos.distanceTo(P.pos)<range&&a.pos.clone().sub(P.pos).setY(0).normalize().dot(dir)>.05&&S.clear(o,a.pos.clone().add(new THREE.Vector3(0,.35,0))))tactics.damageAGV(n*blessings.B.attack,'melee');},structureBlast:(p,r,n)=>{destruction.blast(p,r,n*blessings.B.attack);const a=tactics.getAGV();if(a&&a.pos.distanceTo(p)<r&&S.clear(p,a.pos.clone().add(new THREE.Vector3(0,.35,0))))tactics.damageAGV(n*blessings.B.attack,'pulse');}});
const tactics=makeTactics(THREE,S,{scene,player:P,playerHeight:()=>blessings.B.height,passive:()=>practice,time:()=>gameTime,enemies:()=>enemies,move:moveActor,openDoor:openNearbyDoor,mesh,notify,supply:kind=>{if(kind==='heal'&&P.hp>=100||kind==='armor'&&P.armor>=armorMax())return false;if(kind==='heal')P.hp=Math.min(100,P.hp+30);if(kind==='armor')P.armor=Math.min(armorMax(),P.armor+25);if(kind==='grenade')grenades++;notify('AGV 補給：'+{heal:'生命 +30',armor:'防彈衣 +25',grenade:'手榴彈 +1'}[kind],2);return true;}});
const destruction=makeDestruction(THREE,F,S,D,{scene,player:P,notify,time:()=>gameTime,dropCabinet:b=>placeLoot({x:(b.minX+b.maxX)/2,z:(b.minZ+b.maxZ)/2,w:.4,d:.4,kind:'ground',name:'置物櫃掉落'},[P.pos]),machineExploded:b=>{selectedMachineNames=selectedMachineNames.filter(n=>n!==b.machineName);F.setMachineSelection(selectedMachineNames);for(let i=loot.length-1;i>=0;i--)if(loot[i].support===b.machineName){scene.remove(loot[i].mesh);if(nearestLoot===loot[i])nearestLoot=null;loot.splice(i,1);}explosion(new THREE.Vector3((b.minX+b.maxX)/2,.9,(b.minZ+b.maxZ)/2),CFG.machineBlastRadius,CFG.machineBlastDamage,false,null);},onWallDestroyed:()=>{for(const d of decals){scene.remove(d);d.geometry.dispose();d.material.dispose();}decals.length=0;}});
const hookLine=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xa5e4dd}));scene.add(hookLine);hookLine.visible=false;
function notify(text,seconds=3){$('notice').textContent=text;$('notice').hidden=false;noticeEnd=gameTime+seconds;}
function stats(id=active){const g=gunStats(id,xp[id]||0);return {...g,damage:(g.damage+(paidUpgrades[id]?.damage||0))*blessings.B.attack+Object.values(blessings.B.elements).reduce((a,b)=>a+b,0),mag:Math.ceil(g.mag*blessings.B.mag)+(paidUpgrades[id]?.mag||0)};}
function gain(id,n){if(practice)return;const before=gunLevel(xp[id]||0);xp[id]=(xp[id]||0)+n;pendingXP=true;if(gunLevel(xp[id])>before)notify(GUNS[id].name+' 升級至 Lv.'+gunLevel(xp[id]),4);}
function equipped(id){return inventory[GUNS[id].slot]===id;}
function switchGun(id){if(!id||!equipped(id))return;active=id;reloadEnd=0;avatar.setGun(id);avatar.poseGun(true);if(ammo[id]===undefined)ammo[id]=stats(id).mag;updateHUD();}
const battleAudio=makeBattleAudio();
function sound(freq=180,duration=.08,type='square',gain=.025){battleAudio.tone(freq,duration,type,gain);}
function burst(pos,color,count=6,speed=1.8,life=.5){for(let i=0;i<count&&particles.length<CFG.particleBudget;i++){const o=new THREE.Mesh(sphereGeo,new THREE.MeshBasicMaterial({color}));o.scale.setScalar(.018+Math.random()*.018);o.position.copy(pos);scene.add(o);particles.push({mesh:o,v:new THREE.Vector3((Math.random()-.5)*speed,Math.random()*speed,(Math.random()-.5)*speed),life,initial:life});}}
function trace(a,b,color=0xf4d78b){if(tracers.length>25){const old=tracers.shift();scene.remove(old.mesh);old.mesh.geometry.dispose();old.mesh.material.dispose();}const dir=b.clone().sub(a),distance=dir.length();if(distance<.001)return;dir.normalize();const mesh=new THREE.Mesh(new THREE.CylinderGeometry(CFG.tracerRadius,CFG.tracerRadius,1,6),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.84,depthWrite:false}));mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);mesh.position.copy(a);scene.add(mesh);tracers.push({mesh,start:a.clone(),dir,distance,travel:0,fade:0});}
function mark(hit){if(!hit||hit.kind==='floor')return;const o=new THREE.Mesh(new THREE.CircleGeometry(.028,7),new THREE.MeshBasicMaterial({color:0x353638,side:THREE.DoubleSide}));o.position.copy(hit.point).addScaledVector(hit.normal,.008);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,0,1),hit.normal);scene.add(o);decals.push(o);if(decals.length>CFG.maxDecals){const x=decals.shift();scene.remove(x);x.geometry.dispose();x.material.dispose();}}
function statusName(a){return Object.entries(a.status).filter(([k,v])=>v.end>gameTime).map(([k,v])=>k+' '+Math.ceil(v.end-gameTime)+'s').join(' · ');}
function applyStatus(a,element,owner,gun,source=null){a.status[element]={end:gameTime+5,next:gameTime+1,owner,gun,source:source?.clone?.()||null};}
function showDamageDirection(source){if(!source)return;const toSource=source.clone().sub(P.pos).setY(0);if(toSource.lengthSq()<.001)return;toSource.normalize();const front=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw)),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw));const angle=Math.atan2(toSource.dot(right),toSource.dot(front))*180/Math.PI;$('damageDir').style.transform='translate(-50%,-50%) rotate('+angle+'deg)';$('damageDir').style.opacity='1';damageDirectionEnd=gameTime+.72;}
function damagePlayer(amount,head=false,source=null){if(mode!=='combat'||P.hp<=0||actions.invulnerable()||gameTime<reviveUntil)return;const vulnerable=P.status['雷']?.end>gameTime?1.05:1;const out=armorDamage(P.hp,P.armor,amount*vulnerable,head);P.hp=out.hp;P.armor=out.armor;hurtFlash=.75;showDamageDirection(source);if(P.hp<=0&&blessings.B.revives>0){blessings.B.revives--;P.hp=CFG.playerHP;P.status={};P.flash=0;reviveUntil=gameTime+3;notify('祝福復活 · 滿血恢復 · 3 秒免傷',3);return;}if(P.hp<=0){mode='dead';battleAudio.pauseMusic();keys.clear();fireHeld=false;hook=null;document.exitPointerLock?.();$('shop').hidden=true;$('pause').hidden=false;$('pauseTitle').textContent='防線失守';$('pauseInfo').textContent='完成 '+Math.max(0,wave-1)+' 波 · 擊倒 '+kills+' 名敵人。武器經驗已保留。';$('resume').hidden=true;save();}}
function hurtEnemy(e,damage,owner=true,gun=active,head=false,element=null){if(e.hp<=0)return;damage*=e.status['雷']?.end>gameTime?1.05:1;e.hp-=damage;e.hit=.18;if(owner)actions.number(e.pos,damage);burst(e.pos.clone().add(new THREE.Vector3(0,head?1.55:1.1,0)),0x992f37,5,1.5,.4);if(owner&&GUNS[gun])gain(gun,2);if(element)applyStatus(e,element,owner,gun);if(e.hp<=0&&practice){kills++;actions.kill();respawnPracticeEnemy(e);return;}if(e.hp<=0){e.hp=0;if(e.labelSprite)e.labelSprite.visible=false;e.deadAt=gameTime;kills++;if(owner){actions.kill();const reward=Math.round((70+e.tier*40)*difficulty);money+=reward;if(GUNS[gun])gain(gun,25+e.tier*10);notify('擊倒 '+e.label+' ＋$'+reward,1.5);}if(!e.boss&&!e.creeper)dropWeapon(e.gun,e.pos);e.model.group.rotation.z=Math.PI/2;e.model.group.position.y=.3;sound(130,.08,'triangle');}}
function sphereHit(origin,dir,pos,r,max){const oc=origin.clone().sub(pos),b=oc.dot(dir),c=oc.lengthSq()-r*r,disc=b*b-c;if(disc<0)return null;let t=-b-Math.sqrt(disc);if(t<.002)t=-b+Math.sqrt(disc);return t>.002&&t<max?t:null;}
function playerSphereHit(origin,dir,pos,r,max){const oc=origin.clone().sub(pos),d=dir.clone();oc.y/=blessings.B.height;d.y/=blessings.B.height;const a=d.lengthSq(),b=oc.dot(d),c=oc.lengthSq()-r*r,v=b*b-a*c;if(v<0)return null;let t=(-b-Math.sqrt(v))/a;if(t<.002)t=(-b+Math.sqrt(v))/a;return t>.002&&t<max?t:null;}
function targetRay(origin,dir,max=80,enemyTargets=true,includeBarrels=true){let hit=S.cast(origin,dir,max),limit=hit?.distance||max;if(enemyTargets)for(const e of enemies)if(e.hp>0){for(const [y,r,head]of [[1.55,.2,true],[1.04,.34,false],[.47,.27,false]]){const t=sphereHit(origin,dir,e.pos.clone().add(new THREE.Vector3(0,y*(e.boss?1.2:1),0)),r*(e.boss?1.2:1),limit);if(t!==null){limit=t;hit={enemy:e,head,distance:t,point:origin.clone().addScaledVector(dir,t)};}}}if(includeBarrels)for(const b of barrels)if(b.hp>0){const t=sphereHit(origin,dir,b.pos.clone().add(new THREE.Vector3(0,.42,0)),.3,limit);if(t!==null){limit=t;hit={barrel:b,distance:t,point:origin.clone().addScaledVector(dir,t)};}}const agv=tactics.getAGV();if(agv&&agv.hp>0){const t=sphereHit(origin,dir,agv.pos.clone().add(new THREE.Vector3(0,.35,0)),.40,limit);if(t!==null){hit={agv,distance:t,point:origin.clone().addScaledVector(dir,t)};}}return hit||{distance:max,point:origin.clone().addScaledVector(dir,max)};}
function forward(){return new THREE.Vector3(-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)).normalize();}
function muzzle(){avatar.group.updateMatrixWorld(true);return avatar.weapon.localToWorld(new THREE.Vector3(0,.015,-avatar.weapon.userData.length-.03));}
function fire(){if(mode!=='combat'||shopOpen||actions.busy()||gameTime<lastShot||reloadEnd>0)return;const g=stats();if(!ammo[active]){reload();return;}tactics.hear(P.pos);lastShot=gameTime+g.interval;ammo[active]--;const id=active,eyeDir=new THREE.Vector3();camera.getWorldDirection(eyeDir);const eyeHit=targetRay(camera.position,eyeDir,g.range+5);const origin=muzzle(),baseDir=eyeHit.point.clone().sub(origin).normalize();const near=S.cast(P.pos.clone().add(new THREE.Vector3(0,py(crouched?.85:1.2),0)),origin.clone().sub(P.pos.clone().add(new THREE.Vector3(0,py(crouched?.85:1.2),0))).normalize(),P.pos.clone().add(new THREE.Vector3(0,py(crouched?.85:1.2),0)).distanceTo(origin));
 for(let i=0;i<g.pellets;i++){const dir=baseDir.clone().add(new THREE.Vector3((Math.random()-.5)*g.spread,(Math.random()-.5)*g.spread,(Math.random()-.5)*g.spread).multiplyScalar(aim?.45:1)).normalize(),hit=near||targetRay(origin,dir,g.range);trace(origin,hit.point);if(hit.enemy){const critical=Math.random()<g.crit;hurtEnemy(hit.enemy,g.damage*(hit.head?2:1)*(critical?1.5:1),true,id,hit.head,Math.random()<g.elementChance?g.element:null);for(const element of Object.keys(blessings.B.elements))if(Math.random()<.15)applyStatus(hit.enemy,element,true,id);$('hit').style.opacity='1';fireFlash=.15;if(critical)notify('暴擊！',.6);}else if(hit.agv){tactics.damageAGV(g.damage,'playerGun');}else if(hit.barrel){hit.barrel.hp-=g.damage;hit.barrel.lastGun=id;if(hit.barrel.hp<=0)explodeBarrel(hit.barrel,true,id);}else{destruction.hit(hit,g.damage);if(!hit.body?.destroyed)mark(hit);}}
 burst(origin,0xffdd7f,3,.4,.055);const casing=origin.clone().add(new THREE.Vector3(.12,0,.1));burst(casing,0xc9a351,1,1.2,.4);battleAudio.gun(id);pitch=clamp(pitch+g.recoil*(aim?.6:1)*(P.status['土']?.end>gameTime?1.3:1),-1.0,.85);}
function reload(){if(mode!=='combat'||actions.busy()||reloadEnd>0||ammo[active]>=stats().mag)return;reloadEnd=gameTime+stats().reload;sound(700,.08,'triangle');notify('換彈中…',stats().reload);}
function dropWeapon(id,pos){if(drops.length>=20){disposeGroup(drops.shift().mesh);}const g=gunModel(id);g.position.copy(pos).add(new THREE.Vector3(0,.23,0));g.rotation.set(0,Math.random()*6.28,Math.PI/2);scene.add(g);drops.push({id,pos:pos.clone(),mesh:g,end:gameTime+CFG.dropSeconds,ammo:Math.ceil(GUNS[id].mag*.5)});}
function disposeGroup(g){scene.remove(g);/* geometry and base materials are shared */}
function pickup(){if(tactics.supply())return;if(pickupLoot())return;if(!nearestDrop||mode!=='combat')return;const d=nearestDrop,slot=GUNS[d.id].slot,old=inventory[slot];if(old&&old!==d.id)dropWeapon(old,P.pos);inventory[slot]=d.id;ammo[d.id]=Math.min(stats(d.id).mag,d.ammo);switchGun(d.id);d.end=0;nearestDrop=null;notify('拾取 '+GUNS[d.id].name+' · 同型武器經驗保留');}
function makeBarrel(pos){const group=new THREE.Group();group.position.copy(pos);mesh(group,'cyl',0xb05439,0,.38,0,.23,.72,.23);mesh(group,'cyl',0x4a4240,0,.76,0,.08,.06,.08);for(const h of [.14,.6])mesh(group,'cyl',0x444747,0,h,0,.238,.035,.238);mesh(group,'box',0xe3ba53,0,.39,-.233,.2,.22,.012);scene.add(group);const b={pos:pos.clone(),mesh:group,hp:CFG.barrelHP,exploded:false,lastGun:'pistol'};barrels.push(b);return b;}
function explosion(pos,radius,max,owner,gun,skipPlayer=false){tactics.hear(pos,18);const agv=tactics.getAGV();if(agv&&S.clear(pos,agv.pos.clone().add(new THREE.Vector3(0,.35,0)),true))tactics.damageAGV(explosionFalloff(agv.pos.distanceTo(pos),radius,max),'explosion');if(owner)max*=blessings.B.attack;destruction.blast(pos,radius,max);burst(pos,0xffa743,24,4,.55);burst(pos,0x565451,8,1.5,1.2);battleAudio.explosion(pos.distanceTo(P.pos));if(!skipPlayer){const p=P.pos.clone().add(new THREE.Vector3(0,py(.8),0)),d=p.distanceTo(pos);if(d<radius&&S.clear(pos,p,true))damagePlayer(explosionFalloff(d,radius,max),false,pos);}for(const e of enemies)if(e.hp>0){const p=e.pos.clone().add(new THREE.Vector3(0,.8,0)),d=p.distanceTo(pos);if(d<radius&&S.clear(pos,p,true))hurtEnemy(e,explosionFalloff(d,radius,max),owner,gun);}for(const b of barrels)if(!b.exploded){const p=b.pos.clone().add(new THREE.Vector3(0,.4,0)),d=p.distanceTo(pos);if(d<radius&&S.clear(pos,p,true)){b.hp-=explosionFalloff(d,radius,max);if(b.hp<=0)explodeBarrel(b,owner,gun);}}}
function explodeBarrel(b,owner=true,gun=active,direct=false){if(b.exploded)return;b.exploded=true;b.hp=0;b.mesh.visible=false;if(direct)damagePlayer(CFG.barrelDamage,false,b.pos);explosion(b.pos.clone().add(new THREE.Vector3(0,.4,0)),CFG.barrelRadius,CFG.barrelDamage,owner,gun,direct);}
function throwItem(type){if(mode!=='combat'||actions.busy()||(type==='grenade'?grenades:flashes)<=0)return;if(type==='grenade')grenades--;else flashes--;const origin=P.pos.clone().add(new THREE.Vector3(0,py(crouched?.9:1.25),0)),dir=forward();const g=new THREE.Mesh(sphereGeo,mat(type==='grenade'?0x738251:0xc6d4d6));g.scale.setScalar(.075);g.position.copy(origin);scene.add(g);projectiles.push({type,mesh:g,pos:origin,v:dir.multiplyScalar(7).add(new THREE.Vector3(0,2.5,0)),end:gameTime+(type==='grenade'?CFG.grenadeFuse:CFG.flashFuse),gun:active});sound(400,.08,'triangle');}
function flash(pos){burst(pos,0xffffff,18,2,.2);battleAudio.flash(pos.distanceTo(P.pos));const eye=P.pos.clone().add(new THREE.Vector3(0,py(crouched?1:1.5),0)),d=eye.distanceTo(pos);if(d<CFG.flashRadius&&S.clear(pos,eye)){const facing=forward().dot(pos.clone().sub(eye).normalize()),strength=(1-d/CFG.flashRadius)*(facing>0?.9:.3);P.flash=Math.max(P.flash,5*strength);}for(const e of enemies)if(e.hp>0){const eye=e.pos.clone().add(new THREE.Vector3(0,1.5,0)),d=eye.distanceTo(pos);if(d<CFG.flashRadius&&S.clear(pos,eye)){const direction=new THREE.Vector3(-Math.sin(e.facing),0,-Math.cos(e.facing)),facing=direction.dot(pos.clone().sub(eye).normalize());tactics.forget(e);e.flash=Math.max(e.flash,(1-d/CFG.flashRadius)*(facing>0?5:1.5));}}}
function startHook(){if(mode!=='combat'||actions.busy()||hook||hookCD>0||hookLatch)return;hookLatch=true;const o=P.pos.clone().add(new THREE.Vector3(0,py(crouched?.85:1.25),0)),view=new THREE.Vector3();camera.getWorldDirection(view);const aimHit=targetRay(camera.position,view,15,false),dir=aimHit.point.clone().sub(o).normalize(),hit=targetRay(o,dir,CFG.grappleRange,false);if(hit.distance>=CFG.grappleRange&&!hit.kind&&!hit.barrel){notify('繩索未命中 · 有效距離 5m',1);return;}if(hit.barrel){explodeBarrel(hit.barrel,true,active,true);hookCD=CFG.grappleCooldown;notify('勾中瓦斯桶！承受完整爆炸傷害',2);return;}if(!hit.kind)return;const dest=hit.point.clone().addScaledVector(dir,-.36);dest.y=clamp(dest.y-(py(crouched?.85:1.25)),0,CFG.floorHeight-(py(crouched?1.15:1.72))-.02);hook={point:hit.point.clone(),dest};sound(600,.1,'triangle');}
function endHook(){if(hook){hook=null;hookCD=CFG.grappleCooldown;}hookLine.visible=false;}
function safePoint(center){if(!S.blocked(center.x,0,center.z))return center.clone().setY(0);for(let r=.3;r<15;r+=.3)for(let a=0;a<6.28;a+=.3){const p=new THREE.Vector3(center.x+Math.cos(a)*r,0,center.z+Math.sin(a)*r);if(!S.blocked(p.x,0,p.z))return p;}throw Error('無安全出生點');}
function moveActor(a,dx,dy,dz,h=1.7,r=.22){let moved=false;for(const [axis,n]of [['x',dx],['z',dz],['y',dy]]){const steps=Math.ceil(Math.abs(n)/.06);for(let i=0;i<steps;i++){const old=a.pos.clone(),test=old.clone();test[axis]+=n/steps;test.y=clamp(test.y,0,CFG.floorHeight-h-.02);if(!S.blocked(test.x,test.y,test.z,r,h)){moved=moved||old.distanceToSquared(test)>1e-8;a.pos.copy(test);}else{if(axis==='y'){let lo=0,hi=1;for(let j=0;j<9;j++){const t=(lo+hi)/2,p=old.clone().lerp(test,t);if(S.blocked(p.x,p.y,p.z,r,h))hi=t;else lo=t;}a.pos.copy(old.lerp(test,lo));if(a===P)P.vy=0;}break;}}}return moved;}
function throwBossGrenade(e){const pos=e.pos.clone().add(new THREE.Vector3(0,1.85,0)),target=e.lastKnown.clone().setY(.08),time=clamp(pos.distanceTo(target)/7,.7,1.5),v=target.clone().sub(pos).multiplyScalar(1/time);v.y+=CFG.gravity*time/2;const m=new THREE.Mesh(sphereGeo,new THREE.MeshStandardMaterial({color:0xab7042,emissive:0x000000,roughness:.5}));m.scale.setScalar(.11);m.position.copy(pos);scene.add(m);projectiles.push({boss:true,type:'grenade',mesh:m,pos,v,end:gameTime+CFG.grenadeFuse,gun:null,glow:null});sound(300,.1,'triangle');}

function openNearbyDoor(pos,manual=false){let best=null,bestD=Infinity;for(const d of F.doors){if(d.destroyed)continue;const mid=new THREE.Vector3((d.hinge[0]+d.closed[0])/2,0,(d.hinge[1]+d.closed[1])/2),dist=mid.distanceTo(pos);if(dist<bestD){bestD=dist;best=d;}}if(best&&bestD<1.9){if(manual){best.target=best.target>.5?0:1;best.manualUntil=gameTime+2;}else{best.target=1;best.lastNear=gameTime;}return best;}return null;}

function makeCreeperModel(model){
 for(const child of model.group.children)child.visible=false;
 const green=0x5aa83c,dark=0x163b21;
 mesh(model.group,'box',green,0,1.48,0,.50,.50,.50);
 mesh(model.group,'box',green,0,.91,0,.36,.65,.30);
 for(const x of [-.18,.18])for(const z of [-.16,.16])mesh(model.group,'box',green,x,.28,z,.23,.50,.25);
 for(const x of [-.12,.12])mesh(model.group,'box',dark,x,1.54,-.256,.10,.10,.012);
 mesh(model.group,'box',dark,0,1.40,-.256,.10,.15,.012);
 for(const x of [-.085,.085])mesh(model.group,'box',dark,x,1.34,-.256,.07,.12,.012);
}
function clearCreepers(){
 for(let i=enemies.length-1;i>=0;i--)if(enemies[i].creeper){
  const e=enemies[i];disposeGroup(e.model.group);e.labelTexture?.dispose();e.labelSprite?.material.dispose();enemies.splice(i,1);
 }
}
function tickCreeper(e,dt){
 if(e.hp<=0||mode!=='combat')return;
 const origin=e.pos.clone().add(new THREE.Vector3(0,.9,0));
 const target=P.pos.clone().add(new THREE.Vector3(0,py(.9),0));
 if(e.fuseEnd===null){
  tactics.think(e,dt);
  if(e.flash<=0&&origin.distanceTo(target)<=CFG.creeperTriggerRadius&&S.clear(origin,target)){
   e.fuseEnd=gameTime+CFG.creeperFuse;
   notify('苦力怕即將爆炸！離開 6m 範圍或擊殺它',2);
   sound(900,.15,'triangle');
  }
 }
 if(e.fuseEnd!==null){
  e.awareness='爆炸倒數 '+Math.max(0,e.fuseEnd-gameTime).toFixed(1)+'s';
  e.model.group.scale.setScalar(1+Math.sin(gameTime*30)*.08);
  if(gameTime>=e.fuseEnd){
   e.hp=0;e.deadAt=gameTime;e.model.group.visible=false;
   burst(origin,0x96ef61,24,4,.55);burst(origin,0x565451,8,1.5,1.2);
   battleAudio.explosion(origin.distanceTo(target));
   if(P.hp>0&&origin.distanceTo(target)<=CFG.creeperBlastRadius&&S.clear(origin,target)){
    P.hp/=10;hurtFlash=.9;showDamageDirection(e.pos);
    notify('苦力怕爆炸！當前生命值降為 1/10',3);
   }
  }
 }
 e.model.group.position.copy(e.pos);
}

function spawnEnemy(creeper=false){const boss=!creeper&&!practice&&wave%3===0&&remaining===1;let options=S.candidates(P.pos.clone().setY(0),8,20).filter(p=>!S.blocked(p.x,0,p.z)&&enemies.every(e=>e.hp<=0||p.distanceTo(e.pos)>1)&&barrels.every(b=>b.exploded||p.distanceTo(b.pos)>.8));if(!options.length)options=S.candidates(P.pos.clone().setY(0),5,100).filter(p=>!S.blocked(p.x,0,p.z)&&enemies.every(e=>e.hp<=0||p.distanceTo(e.pos)>1));if(!options.length)return false;let p=options[Math.floor(Math.random()*options.length)];for(let i=0;i<10;i++){const q=options[Math.floor(Math.random()*options.length)];if(!S.clear(P.pos.clone().add(new THREE.Vector3(0,py(1.4),0)),q.clone().add(new THREE.Vector3(0,1.4,0)))){p=q;break;}}
 const tier=boss||creeper?0:wave>=4&&Math.random()<.3?2:wave>=2&&Math.random()<.4?1:0,gun=tier===2?'sniper':tier===1?'rifle':Math.random()<.5?'pistol':'smg',model=actor(true);model.setGun(gun);if(creeper)makeCreeperModel(model);if(boss){model.poseGun(false);model.weapon.visible=false;mesh(model.group,'box',0xb65d37,0,1.10,-.18,.34,.30,.045);mesh(model.group,'sphere',0xa87945,.28,1.03,-.27,.10,.10,.10);}model.group.position.copy(p);const e={pos:p.clone(),model,hp:(65+tier*35)*(1+Math.min(wave-1,15)*.1),maxHP:(65+tier*35)*(1+Math.min(wave-1,15)*.1),boss,creeper,fuseEnd:null,gun,tier,label:creeper?'苦力怕':boss?'BOSS 擲彈兵':['巡邏兵','突擊兵','精銳'][tier],cooldown:1+Math.random(),status:{},flash:0,hit:0,think:0,visible:false,deadAt:0,stuck:0,ammo:GUNS[gun].mag,reload:0};const canvas=document.createElement('canvas');canvas.width=256;canvas.height=80;const tex=new THREE.CanvasTexture(canvas);e.labelCanvas=canvas;e.labelTexture=tex;e.labelLast='';const label=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,depthTest:true,transparent:true}));label.position.set(0,1.98,0);label.scale.set(1.3,.406,1);e.model.group.add(label);e.labelSprite=label;if(boss){e.hp*=2;e.maxHP*=2;}tactics.init(e);enemies.push(e);if(!creeper)remaining--;return true;}
function tickEnemies(dt){for(let i=enemies.length-1;i>=0;i--){const e=enemies[i];if(e.hp<=0){if(gameTime-e.deadAt>2){disposeGroup(e.model.group);e.labelTexture?.dispose();e.labelSprite?.material.dispose();enemies.splice(i,1);}continue;}const labelKey=Math.ceil(e.hp)+'|'+e.awareness+'|'+statusName(e);if(labelKey!==e.labelLast){e.labelLast=labelKey;const c=e.labelCanvas.getContext('2d');c.clearRect(0,0,256,80);c.fillStyle='#102830dd';c.fillRect(0,0,256,80);c.fillStyle='#f5dcc2';c.font='bold 23px sans-serif';c.textAlign='center';c.fillText(e.label+(e.flash>.2?' · 致盲':''),128,26);c.fillStyle='#5a3435';c.fillRect(12,37,232,10);c.fillStyle='#e88679';c.fillRect(12,37,232*clamp(e.hp/e.maxHP,0,1),10);c.fillStyle='#eecb83';c.font='18px sans-serif';c.fillText(e.awareness+' '+statusName(e),128,70);e.labelTexture.needsUpdate=true;}e.flash=Math.max(0,e.flash-dt);e.hit=Math.max(0,e.hit-dt);e.cooldown-=dt;e.think-=dt;e.reload=Math.max(0,e.reload-dt);e.model.group.scale.setScalar((e.boss?1.2:1)*(e.hit>0?.96:1));if(e.creeper){tickCreeper(e,dt);continue;}const distance=tactics.think(e,dt);
 if(e.boss){e.model.poseGun(false);if(!practice&&e.visible&&e.flash<.2&&e.cooldown<=0){throwBossGrenade(e);e.cooldown=3.8;}e.model.group.position.copy(e.pos);e.model.arms[0].rotation.x=-.4;e.model.arms[1].rotation.x=e.cooldown>3.4?-2.2:-.4;continue;}
 if(!practice&&e.visible&&e.flash<.2&&e.cooldown<=0&&e.reload<=0){if(e.ammo<=0){e.reload=GUNS[e.gun].reload;e.ammo=GUNS[e.gun].mag;}else{e.ammo--;e.cooldown=clamp(.8-.04*wave,.28,.8)/(difficulty*.8);const origin=e.pos.clone().add(new THREE.Vector3(.1,1.25,0)),target=P.pos.clone().add(new THREE.Vector3(0,py(crouched?.7:1.18),0));const spread=(.17+distance*.035)*(e.status['土']?.end>gameTime?1.3:1)/difficulty;target.add(new THREE.Vector3((Math.random()-.5)*spread,(Math.random()-.5)*spread,(Math.random()-.5)*spread));const dir=target.clone().sub(origin).normalize(),length=origin.distanceTo(target),wall=targetRay(origin,dir,length+.5,false);let t=null,head=false;for(const [height,r,isHead]of [[crouched?1:1.55,.18,true],[crouched?.6:1,.32,false]]){const n=playerSphereHit(origin,dir,P.pos.clone().add(new THREE.Vector3(0,py(height),0)),r,wall?.distance||length+.5);if(n!==null&&(t===null||n<t)){t=n;head=isHead;}}trace(origin,wall?.point||target,0xf08865);if(t===null&&wall?.agv)tactics.damageAGV(10*difficulty,'enemyGun');if(t===null&&wall?.body)destruction.hit(wall,10*difficulty);if(wall?.barrel&&t===null){wall.barrel.hp-=10*difficulty;if(wall.barrel.hp<=0)explodeBarrel(wall.barrel,false,e.gun);}if(t!==null&&Math.random()<CFG.enemyHitChance){damagePlayer((7+e.tier*3)*difficulty*(head?1.7:1),head,e.pos);if(difficulty>=1.6&&Math.random()<.18)applyStatus(P,GUNS[e.gun].element,false,e.gun,e.pos);}battleAudio.gun(e.gun,distance,.45);}}
 e.model.group.position.copy(e.pos);e.model.arms[0].rotation.x=-.7;e.model.arms[1].rotation.x=-1.1;e.model.poseGun(true,e.reload>0);}}
function tickStatuses(a,dt,isPlayer){for(const [kind,s]of Object.entries(a.status)){if(kind==='火')while(s.next<=gameTime&&s.next<=s.end){s.next+=1;if(isPlayer){if(mode!=='combat')break;damagePlayer(CFG.playerHP*.03,false,s.source);}else if(a.hp>0)hurtEnemy(a,a.maxHP*.03,s.owner,s.gun);}if(gameTime>=s.end)delete a.status[kind];}}
function clearRound(){creeperSpawned=false;tactics.clear();destruction.reset();actions.reset();clearLoot();for(const list of [enemies,barrels,drops,projectiles,particles,tracers]){for(const o of list){disposeGroup(o.mesh||o.model?.group);if(list===enemies){o.labelTexture?.dispose();o.labelSprite?.material.dispose();}if(o.glow){scene.remove(o.glow);o.glow.geometry.dispose();o.glow.material.dispose();}if(list===projectiles&&o.boss)o.mesh.material.dispose();if(list===particles)o.mesh.material.dispose();if(list===tracers){o.mesh.geometry.dispose();o.mesh.material.dispose();}}list.length=0;}for(const d of decals){scene.remove(d);d.geometry.dispose();d.material.dispose();}decals.length=0;}
const loot=[],lootKinds={heal:{name:'補血 +30',color:0x69c8a2},armor:{name:'防彈衣 +25',color:0x75a3dc},grenade:{name:'手榴彈 +1',color:0xa6b766},flash:{name:'閃光彈 +1',color:0xe3d69c},cash:{name:'金錢 +150',color:0xf0bc59}};
let selectedMachineNames=[],nearestLoot=null;
function shuffled(list){const a=list.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function clearLoot(){for(const l of loot)scene.remove(l.mesh);loot.length=0;nearestLoot=null;}
function placeLoot(o,candidates){
 const yaw=o.yaw||0,c=Math.cos(yaw),s=Math.sin(yaw),h=o.kind==='machine'?1.80:o.kind==='ground'?0:.715;
 // Put the box on the closest exposed edge, not at an unreachable cabinet centre.
 let access=null;const ordered=candidates.map(p=>({p,d:Math.hypot(p.x-o.x,p.z-o.z)})).sort((a,b)=>a.d-b.d);
 for(const {p} of ordered){if(S.clear(p.clone().setY(1.55),new THREE.Vector3(o.x,h+.2,o.z),true)){access=p;break;}}
 if(!access)access=P.pos;
 const dx=access.x-o.x,dz=access.z-o.z,lx=clamp(dx*c+dz*s,-o.w/2+.16,o.w/2-.16),lz=clamp(-dx*s+dz*c,-o.d/2+.16,o.d/2-.16);
 const pos=new THREE.Vector3(o.x+lx*c-lz*s,h+.10,o.z+lx*s+lz*c),kind=Object.keys(lootKinds)[Math.floor(Math.random()*5)],g=new THREE.Group();g.position.copy(pos);g.name='Loot_'+kind;
 mesh(g,'box',lootKinds[kind].color,0,0,0,.22,.20,.22);mesh(g,'box',0xf7f3df,0,.102,0,.055,.006,.22);mesh(g,'box',0xf7f3df,0,.103,0,.22,.006,.055);scene.add(g);loot.push({kind,pos,mesh:g,support:o.name||'貨架',supportKind:o.kind,access:access.clone()});
}
function refreshWaveLayout(){
 clearLoot();endHook();nearestDrop=null;
 for(const d of drops)scene.remove(d.mesh);drops.length=0;
 for(const d of decals){scene.remove(d);d.geometry.dispose();d.material.dispose();}decals.length=0;
 const burningNames=new Set([...destruction.burning].map(b=>b.machineName));const available=D.objects.filter(o=>o.kind==='machine'&&!destruction.exploded.has(o.name));const kept=[...available.filter(o=>burningNames.has(o.name)),...shuffled(available.filter(o=>!burningNames.has(o.name)))].slice(0,50);selectedMachineNames=kept.map(o=>o.name);
 F.setMachineSelection(selectedMachineNames);S.setMachineSelection(selectedMachineNames);destruction.resetMachines();
 if(S.blocked(P.pos.x,P.pos.y,P.pos.z)){P.pos.copy(safePoint(P.pos));P.vy=0;}
 S.flow(P.pos);
 for(const b of barrels)if(!b.exploded&&S.blocked(b.pos.x,0,b.pos.z,.3,.8)){b.pos.copy(safePoint(b.pos));b.mesh.position.copy(b.pos);}
 resizePlayer();const accessPoints=S.candidates(P.pos,0,999);
 for(const o of shuffled(kept.filter(o=>!burningNames.has(o.name))).slice(0,10))placeLoot(o,accessPoints);
 for(const o of shuffled(D.objects.filter(o=>o.kind==='rack')).slice(0,Math.round(D.objects.filter(o=>o.kind==='rack').length*.25)))placeLoot(o,accessPoints);
}
function lootInReach(l){const hand=P.pos.clone().add(new THREE.Vector3(0,py(1.3),0));return hand.distanceTo(l.pos)<1.85&&S.clear(hand,l.pos,true);}
function pickupLoot(){if(!nearestLoot||!['buy','combat'].includes(mode)||shopOpen)return false;const l=nearestLoot;if(!loot.includes(l)||!lootInReach(l))return false;
 if(l.kind==='heal'&&P.hp>=100||l.kind==='armor'&&P.armor>=armorMax()||l.kind==='grenade'&&grenades>=5||l.kind==='flash'&&flashes>=5){notify('已達上限，道具保留',1);return true;}
 if(l.kind==='heal')P.hp=Math.min(100,P.hp+30);else if(l.kind==='armor')P.armor=Math.min(armorMax(),P.armor+25);else if(l.kind==='grenade')grenades++;else if(l.kind==='flash')flashes++;else money+=150;
 scene.remove(l.mesh);loot.splice(loot.indexOf(l),1);nearestLoot=null;notify('取得 '+lootKinds[l.kind].name,1.5);return true;}
function playTimeText(){const n=Math.floor(gameTime);return [Math.floor(n/3600),Math.floor(n/60)%60,n%60].map(v=>String(v).padStart(2,'0')).join(':');}
function beginBuy(){clearCreepers();creeperSpawned=false;actions.reset();mode='buy';phaseTime=CFG.buySeconds;wave++;blessings.offer(wave);remaining=4+wave*2;refreshWaveLayout();tactics.spawnAGV();notify('第 '+wave+' 波準備 · 20 秒購買 · 保留 50 台機台',3);openShop();}
function startGame(training=false){practice=training===true;touchReset();battleAudio.unlock();battleAudio.resumeMusic();paidUpgrades={};blessings.reset();reviveUntil=0;clearRound();wave=0;kills=0;money=CFG.startMoney;gameTime=0;P.pos.copy(safePoint(new THREE.Vector3(D.spawn[0],0,D.spawn[1])));P.hp=CFG.playerHP;P.armor=0;P.fuel=100;P.vy=0;P.status={};P.flash=0;hook=null;hookCD=0;hookLatch=false;jumpLatch=false;grounded=true;keys.clear();fireHeld=false;aim=false;grenades=2;flashes=2;inventory={side:'pistol',main:null};ammo={pistol:gunStats('pistol',xp.pistol||0).mag};reloadEnd=0;lastShot=0;yaw=Math.PI;pitch=-.12;difficulty=Number($('difficulty').value);for(const d of F.doors){if(d.destroyed)continue;d.t=0;d.target=0;d.manualUntil=0;}S.flow(P.pos);const candidates=S.candidates(P.pos,4,26);for(let tries=0;tries<200&&barrels.length<CFG.barrelCount;tries++){const p=candidates[Math.floor(Math.random()*candidates.length)];if(p&&!S.blocked(p.x,0,p.z,.34,.8)&&barrels.every(b=>b.pos.distanceTo(p)>2.3))makeBarrel(p);}switchGun('pistol');$('menu').hidden=true;$('pause').hidden=true;$('resume').hidden=false;if(practice){wave=1;remaining=5;phaseTime=0;refreshWaveLayout();mode='combat';closeShop(false);for(let i=0;i<5;i++)spawnEnemy();notify('射擊練習場 · 五名移動敵人 · 擊倒立即重生',4);requestLock();}else beginBuy();$('leavePractice').hidden=!practice;$('shopBtn').hidden=practice;avatar.group.visible=true;updateCamera(1);updateHUD();}

function respawnPracticeEnemy(e){
 const old=e.pos.clone();
 const points=S.candidates(P.pos.clone().setY(0),0,999).filter(p=>p.distanceTo(P.pos)>3&&p.distanceTo(old)>2&&!S.blocked(p.x,0,p.z,.22,1.7)&&enemies.every(other=>other===e||other.hp<=0||p.distanceTo(other.pos)>1)&&barrels.every(b=>b.exploded||p.distanceTo(b.pos)>.8));
 // The previous valid spawn remains a fallback if the entire navigation region is obstructed.
 e.pos.copy(points.length?points[Math.floor(Math.random()*points.length)]:safePoint(old));
 e.hp=e.maxHP;e.status={};e.flash=0;e.hit=0;e.deadAt=0;e.stuck=0;e.reload=0;e.ammo=GUNS[e.gun].mag;e.cooldown=1;e.labelLast='';e.labelSprite.visible=true;e.model.group.rotation.z=0;e.model.group.position.copy(e.pos);tactics.init(e);
}
function leaveToMenu(){mode='menu';practice=false;touchReset();keys.clear();fireHeld=false;aim=false;reloadEnd=0;endHook();shopOpen=false;nearestDrop=null;nearestDoor=null;battleAudio.pauseMusic();clearRound();save();$('shop').hidden=true;$('pause').hidden=true;$('leavePractice').hidden=true;$('shopBtn').hidden=false;$('touchControls').hidden=true;$('menu').hidden=false;document.exitPointerLock?.();updateHUD();}

function shopItem(key){if(mode!=='buy'||phaseTime<=0)return;let price=0;if(GUNS[key])price=GUNS[key].price;else price=CFG.shopPrices[key];if(price===undefined||money<price){notify('金錢不足');return;}if(key==='armor'&&P.armor>=armorMax()||key==='heal'&&P.hp>=100||key==='grenade'&&grenades>=5||key==='flash'&&flashes>=5){notify('已達上限');return;}money-=price;if(GUNS[key]){inventory[GUNS[key].slot]=key;ammo[key]=stats(key).mag;switchGun(key);}else if(key==='armor')P.armor=armorMax();else if(key==='heal')P.hp=Math.min(100,P.hp+50);else if(key==='grenade')grenades++;else if(key==='flash')flashes++;renderShop();sound(800,.08,'sine');}
function renderShop(){renderUpgrades();blessings.render($('blessingShop'));const items=$('shopItems');items.replaceChildren();const list=[...Object.keys(GUNS).filter(k=>k!=='pistol'),'armor','grenade','flash','heal'];for(const key of list){const g=GUNS[key],s=g?stats(key):null,price=g?g.price:CFG.shopPrices[key],el=document.createElement('div');el.className='item';const name=g?g.name:{armor:'防彈衣 · 補滿'+armorMax(),grenade:'手榴彈 ＋1',flash:'閃光彈 ＋1',heal:'醫療補給 ＋50 HP'}[key];el.innerHTML='<b>'+name+'</b><div class="muted">'+(g?'Lv.'+s.level+' · 傷害 '+s.damage.toFixed(0)+' · 彈匣 '+s.mag+'<br>Lv.3 解鎖 '+g.element+' 屬性':key==='armor'?'身體減傷45%，頭部不受保護':key==='heal'?'生命上限100':'最多攜帶5枚')+'</div>';const b=document.createElement('button');b.textContent='$'+price+' 購買';b.disabled=money<price||(g&&inventory.main===key);b.onclick=()=>shopItem(key);el.append(b);items.append(el);}$('shopMoney').textContent='持有 $'+money;}
function upgradeWeapon(id,kind){if(mode!=='buy'||phaseTime<=0||!GUNS[id]||!equipped(id)||!['damage','mag'].includes(kind))return false;const price=kind==='damage'?100:500;if(money<price){notify('金錢不足');return false;}const u=paidUpgrades[id]||(paidUpgrades[id]={damage:0,mag:0});money-=price;const value=kind==='damage'?1:id==='sniper'?1:5;u[kind]+=value;notify(GUNS[id].name+(kind==='damage'?' 攻擊力 +':' 彈匣容量 +')+value,2);renderShop();updateHUD();return true;}
function renderUpgrades(){const root=$('upgradeShop');root.replaceChildren();const title=document.createElement('h3');title.textContent='付費武器強化 · 本局持續';root.append(title);for(const id of [inventory.side,inventory.main].filter(Boolean)){const g=stats(id),u=paidUpgrades[id]||{damage:0,mag:0},row=document.createElement('div');row.className='item';const label=document.createElement('b');label.textContent=GUNS[id].name+' · 傷害 '+g.damage.toFixed(1)+' · 彈匣 '+g.mag;row.append(label);const note=document.createElement('p');note.className='muted';note.textContent='已強化：攻擊 +'+u.damage+'／彈匣 +'+u.mag+'。擴充後換彈裝滿；同型槍保留強化。';row.append(note);for(const kind of ['damage','mag']){const button=document.createElement('button');button.textContent=kind==='damage'?'$100 · 攻擊 +1':'$500 · 彈匣 +'+(id==='sniper'?1:5);button.disabled=money<(kind==='damage'?100:500);button.onclick=()=>upgradeWeapon(id,kind);row.append(button);}root.append(row);}}
function openShop(){touchReset();if(mode!=='buy'){notify('只能在每波開始前購買');return;}shopOpen=true;keys.clear();fireHeld=false;aim=false;document.exitPointerLock?.();$('shop').hidden=false;renderShop();}
function closeShop(lock=true){shopOpen=false;$('shop').hidden=true;document.activeElement?.blur?.();if(lock)requestLock();}
function requestLock(){if(mobile)return;try{const p=renderer.domElement.requestPointerLock?.();if(p?.catch)p.catch(()=>notify('可按住左鍵拖曳轉向；建議允許滑鼠鎖定'));}catch(e){}}
function pauseGame(info=''){touchReset();if(mode==='paused'||mode==='menu'||mode==='dead')return;previousMode=mode;mode='paused';battleAudio.pauseMusic();keys.clear();fireHeld=false;aim=false;endHook();shopOpen=false;$('shop').hidden=true;document.exitPointerLock?.();$('pause').hidden=false;$('resume').hidden=false;$('pauseTitle').textContent='已暫停';$('pauseInfo').textContent=info||'暫停期間波次倒數、燃料與敵人皆停止。';}
function resume(){if(mode!=='paused')return;mode=previousMode;battleAudio.resumeMusic();$('pause').hidden=true;requestLock();}
function tickPlayer(dt){const old=P.pos.clone();crouched=keys.has('ControlLeft')||keys.has('ControlRight');const h=py(crouched?1.12:1.72);if(!crouched&&S.blocked(P.pos.x,P.pos.y,P.pos.z,.22,h)){crouched=true;}const height=py(crouched?1.12:1.72);if(S.blocked(P.pos.x,P.pos.y,P.pos.z,.22,height))resizePlayer();const slow=P.status['水']?.end>gameTime?.9:1,speed=(crouched?CFG.crouch:keys.has('ShiftLeft')||keys.has('ShiftRight')?CFG.run:CFG.walk)*slow*blessings.B.speed;let x=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),norm=Math.hypot(x,z)||1;x/=norm;z/=norm;
 if(hook){if(!keys.has('KeyV'))endHook();else{const dir=hook.dest.clone().sub(P.pos),len=dir.length();if(len<.12)endHook();else{dir.normalize().multiplyScalar(Math.min(len,CFG.walk*CFG.grappleSpeed*dt));if(!moveActor(P,dir.x,dir.y,dir.z,height))endHook();P.vy=0;}}}else if(!actions.dashing())moveActor(P,(Math.cos(yaw)*x-Math.sin(yaw)*z)*speed*dt,0,(-Math.sin(yaw)*x-Math.cos(yaw)*z)*speed*dt,height);
 const below=P.pos.y<=.005||S.blocked(P.pos.x,P.pos.y-.04,P.pos.z,.2,height);grounded=below&&P.vy<=0;jet=false;if(!hook){if(grounded&&keys.has('Space')&&!jumpLatch&&P.vy<=0){jumpLatch=true;P.vy=CFG.jump;grounded=false;}if(!grounded&&keys.has('Space')&&P.fuel>0){jet=true;P.fuel=Math.max(0,P.fuel-CFG.jetDrain*dt);P.vy=CFG.jetRise;}else if(!grounded)P.vy-=CFG.gravity*dt;
 if(grounded){P.vy=0;P.fuel=Math.min(100,P.fuel+CFG.jetFill*dt);}moveActor(P,0,P.vy*dt,0,height);if(P.pos.y<=0)P.vy=0;}
 if(keys.has('KeyV'))startHook();hookCD=Math.max(0,hookCD-dt);
 if(jet&&Math.random()<.4)burst(P.pos.clone().add(new THREE.Vector3(Math.sin(yaw)*.2,py(.8),Math.cos(yaw)*.2)),0x8ed8ed,1,.5,.18);
 step+=old.distanceTo(P.pos)*7;avatar.group.position.copy(P.pos);avatar.group.rotation.y=yaw;avatar.group.scale.y=(crouched?.65:1)*blessings.B.height;avatar.legs[0].rotation.x=Math.sin(step)*.43;avatar.legs[1].rotation.x=-avatar.legs[0].rotation.x;avatar.arms[0].rotation.x=-.8;avatar.arms[1].rotation.x=-1.1;avatar.mount.rotation.x=pitch;
 if(reloadEnd>0){const g=stats(),progress=1-(reloadEnd-gameTime)/g.reload;avatar.mount.rotation.z=Math.sin(clamp(progress,0,1)*Math.PI)*-.8;avatar.arms[0].rotation.x=-.2;avatar.weapon.userData.magazine.position.y=-.115-Math.sin(progress*Math.PI)*.24;if(gameTime>=reloadEnd){ammo[active]=g.mag;reloadEnd=0;avatar.mount.rotation.z=0;avatar.weapon.userData.magazine.position.y=-.115;sound(550,.09,'triangle');}}else avatar.mount.rotation.z*=.8;
 nearestDoor=null;let best=1.8;for(const d of F.doors){if(d.destroyed)continue;const distance=Math.hypot(P.pos.x-(d.hinge[0]+d.closed[0])/2,P.pos.z-(d.hinge[1]+d.closed[1])/2);if(distance<best){best=distance;nearestDoor=d;}if(d.automatic&&distance<1.65){d.target=1;d.lastNear=gameTime;}}
 nearestDrop=null;best=1.6;for(const d of drops)if(d.end>gameTime){const distance=d.pos.distanceTo(P.pos);if(distance<best){best=distance;nearestDrop=d;}}
 nearestLoot=null;let lootDistance=Infinity;for(const l of loot)if(lootInReach(l)){const d=l.pos.distanceTo(P.pos);if(d<lootDistance){lootDistance=d;nearestLoot=l;}}
 const agv=tactics.getAGV(),nearAGV=agv&&agv.hp>0&&agv.supplies>0&&agv.pos.distanceTo(P.pos)<1.7;$('prompt').hidden=!nearestDoor&&!nearestDrop&&!nearestLoot&&!nearAGV;$('prompt').textContent=nearAGV?'F 領取 AGV 補給 · 剩餘 '+agv.supplies:nearestLoot?'F 取得 '+lootKinds[nearestLoot.kind].name+' · '+nearestLoot.support:nearestDrop?'F 拾取 '+GUNS[nearestDrop.id].name+' · '+Math.ceil(nearestDrop.end-gameTime)+'s':nearestDoor?'E '+(nearestDoor.target>.5?'關門':'開門'):'';
 if(hook){hookLine.visible=true;hookLine.geometry.setFromPoints([P.pos.clone().add(new THREE.Vector3(0,py(1.1),0)),hook.point]);}else hookLine.visible=false;
}
function tickDoors(dt){for(const d of F.doors){if(d.destroyed)continue;if(d.automatic&&gameTime-(d.lastNear||0)>2&&gameTime>(d.manualUntil||0))d.target=0;const old=d.t;d.t+=Math.sign(d.target-d.t)*Math.min(Math.abs(d.target-d.t),dt*2.6);if(d.t<old&&[P,...enemies.filter(e=>e.hp>0)].some(a=>S.blocked(a.pos.x,a.pos.y,a.pos.z,.23,a===P?py(crouched?1.12:1.72):1.72))){d.t=old;d.target=1;}if(d.type==='sliding'){d.group.position.set(d.hinge[0]+d.slide[0]*d.t,0,d.hinge[1]+d.slide[1]*d.t);}else d.group.rotation.y=-(d.angle+d.swing*d.t);}}
function tickEffects(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;p.v.y-=5*dt;p.mesh.position.addScaledVector(p.v,dt);p.mesh.scale.multiplyScalar(Math.max(.7,1-dt*.8));if(p.life<=0){scene.remove(p.mesh);p.mesh.material.dispose();particles.splice(i,1);}}for(let i=tracers.length-1;i>=0;i--){const t=tracers[i];if(t.travel<t.distance){t.travel=Math.min(t.distance,t.travel+CFG.tracerSpeed*dt);t.mesh.position.copy(t.start).addScaledVector(t.dir,t.travel*.5);t.mesh.scale.set(1,t.travel,1);}else{t.fade+=dt;t.mesh.material.opacity=Math.max(0,.84-t.fade*10);}if(t.fade>.1){scene.remove(t.mesh);t.mesh.geometry.dispose();t.mesh.material.dispose();tracers.splice(i,1);}}$('damageDir').style.opacity=damageDirectionEnd>gameTime?String(Math.min(1,(damageDirectionEnd-gameTime)/.16)):'0';
 for(let i=drops.length-1;i>=0;i--){const d=drops[i];d.mesh.position.y=.25+Math.sin(gameTime*3)*.045;if(d.end-gameTime<3)d.mesh.visible=Math.sin(gameTime*15)>0;if(d.end<=gameTime){disposeGroup(d.mesh);drops.splice(i,1);}}
 for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.v.y-=CFG.gravity*dt;const travel=p.v.clone().multiplyScalar(dt),len=travel.length(),hit=S.cast(p.pos,travel.clone().normalize(),len+.08);if(hit){if(p.boss&&hit.kind==='floor'&&!p.glow){p.mesh.material.emissive.setHex(0xffb43b);p.mesh.material.emissiveIntensity=2;const ring=new THREE.Mesh(new THREE.RingGeometry(.13,.26,24),new THREE.MeshBasicMaterial({color:0xffb43b,transparent:true,opacity:.8,side:THREE.DoubleSide,depthWrite:false}));ring.rotation.x=-Math.PI/2;scene.add(ring);p.glow=ring;}p.pos.copy(hit.point).addScaledVector(hit.normal,.09);p.v.reflect(hit.normal).multiplyScalar(.45);if(p.v.length()<.2)p.v.set(0,0,0);}else p.pos.add(travel);p.mesh.position.copy(p.pos);p.mesh.rotation.x+=dt*7;if(p.glow){p.glow.position.set(p.pos.x,.012,p.pos.z);p.glow.material.opacity=.55+.4*Math.sin(gameTime*15);}if(gameTime>=p.end){scene.remove(p.mesh);if(p.glow){scene.remove(p.glow);p.glow.geometry.dispose();p.glow.material.dispose();}if(p.boss)p.mesh.material.dispose();if(p.type==='grenade')explosion(p.pos,CFG.grenadeRadius,CFG.grenadeDamage,!p.boss,null);else flash(p.pos);projectiles.splice(i,1);}}
 fireFlash=Math.max(0,fireFlash-dt);$('hit').style.opacity=fireFlash>0?'1':'0';hurtFlash=Math.max(0,hurtFlash-dt);$('hurt').style.opacity=String(hurtFlash);P.flash=Math.max(0,P.flash-dt);$('effects').style.opacity=String(Math.min(.98,P.flash/2));}
function updateCamera(dt){const head=P.pos.clone().add(new THREE.Vector3(0,py(crouched?.95:1.48),0)),dir=forward(),right=new THREE.Vector3(Math.cos(yaw),0,-Math.sin(yaw)),distance=aim?1.05:2.8;const desired=head.clone().addScaledVector(dir,-distance).addScaledVector(right,aim?.38:.58).add(new THREE.Vector3(0,.22,0));desired.y=clamp(desired.y,.25,CFG.floorHeight-.15);const ray=desired.clone().sub(head),hit=S.cast(head,ray.clone().normalize(),ray.length());if(hit)desired.copy(hit.point).addScaledVector(ray.normalize(),-.16);camera.position.copy(desired);camera.lookAt(head.clone().addScaledVector(dir,20));camera.fov=aim?(active==='sniper'?35:50):actions.dashing()?69:66+actions.shake()*8;camera.updateProjectionMatrix();}
function tick(dt){if(mode!=='buy'&&mode!=='combat')return;gameTime+=dt;saveTimer+=dt;if(pendingXP&&saveTimer>2){save();pendingXP=false;saveTimer=0;}if(mode==='buy'){if(!blessings.pending())phaseTime-=dt;if(phaseTime<=0){mode='combat';phaseTime=0;closeShop(false);notify('第 '+wave+' 波開始！點擊場景鎖定滑鼠',3);requestLock();spawnTimer=0;}}tickPlayer(dt);actions.tick(dt);avatar.poseGun(!actions.state().attacking,reloadEnd>0);avatar.group.position.copy(P.pos);tickDoors(dt);if(mode==='combat'){if(!practice&&wave%10===0&&!creeperSpawned)creeperSpawned=spawnEnemy(true);flowTimer-=dt;if(flowTimer<=0){S.flow(P.pos);flowTimer=.65;}spawnTimer-=dt;if(remaining>0&&enemies.filter(e=>e.hp>0&&!e.creeper).length<CFG.maxEnemies&&spawnTimer<=0){spawnTimer=1.2;spawnEnemy();}tickEnemies(dt);tickStatuses(P,dt,true);for(const e of enemies)if(e.hp>0)tickStatuses(e,dt,false);if(fireHeld&&!shopOpen)fire();if(!practice&&mode==='combat'&&remaining<=0&&!enemies.some(e=>e.hp>0&&!e.creeper)){money+=Math.round(150*difficulty);beginBuy();}}
 tactics.tickAGV(dt);tickEffects(dt);destruction.tick(gameTime);const burn=destruction.nearBurn(P.pos);if(burn)damagePlayer(3*dt,false,burn);updateCamera(dt);if(gameTime>noticeEnd)$('notice').hidden=true;}
function updateHUD(){if(mobile)$('touchControls').hidden=shopOpen||!['buy','combat'].includes(mode);const view=new THREE.Vector3();camera.getWorldDirection(view);$('structureHP').textContent=destruction.label(targetRay(camera.position,view,30));const a=actions.state();$('actionEnergy').textContent='行動能量 '+Math.floor(a.energy)+' / 100';$('energyBar').style.width=a.energy+'%';$('actionCooldown').textContent='Alt 閃避 '+(a.dashCooldown?a.dashCooldown.toFixed(1)+'s':'就緒')+' · C 衝擊波 '+(a.pulseCooldown?a.pulseCooldown.toFixed(1)+'s':'就緒');const g=stats();$('playTime').textContent='遊玩時間 '+playTimeText()+' · 機台 '+selectedMachineNames.length+' / 50 · 道具 '+loot.length;$('healthText').textContent='生命 '+Math.ceil(P.hp)+' / 100';$('armorText').textContent='防彈衣 '+Math.ceil(P.armor)+' / '+armorMax();$('fuelText').textContent='噴射器 '+Math.floor(P.fuel)+'%'+(jet?' · 噴射中':'');$('healthBar').style.width=clamp(P.hp,0,100)+'%';$('armorBar').style.width=(P.armor/armorMax()*100)+'%';$('fuelBar').style.width=P.fuel+'%';$('hookText').textContent=hook?'繩索拉動中':hookCD>0?'繩索冷卻 '+hookCD.toFixed(1)+'s':'V 按住繩索 · 5m';$('money').textContent='$ '+money+' · 擊倒 '+kills;$('consumables').textContent='G 手榴彈 '+grenades+'　Q 閃光彈 '+flashes;$('statuses').textContent=statusName(P)+' · 復活 '+blessings.B.revives+' 次'+(gameTime<reviveUntil?' · 復活保護中':'');$('gunName').textContent=g.name+' · Lv.'+g.level;$('ammo').textContent=reloadEnd>0?'換彈 '+Math.max(0,reloadEnd-gameTime).toFixed(1)+'s':(ammo[active]??g.mag)+' / '+g.mag+' ∞';$('xpText').textContent='XP '+Math.floor(xp[active]||0)+' · '+(g.level>=CFG.maxLevel?'滿級': '下一級 '+(80*g.level*g.level))+' · '+g.element+(g.elementChance?' '+Math.round(g.elementChance*100)+'%':' Lv.3解鎖');$('gunStats').textContent='傷害 '+g.damage.toFixed(0)+' · 暴擊 '+Math.round(g.crit*100)+'%';$('phase').textContent=practice&&mode==='combat'?'射擊練習場 · 移動敵人 5 名 · 擊倒 '+kills:mode==='buy'?'第 '+wave+' 波 · '+(blessings.pending()?'請至商店選祝福':'購買 '+Math.ceil(phaseTime)+'s'):mode==='combat'?'第 '+wave+' 波 · 剩餘敵人 '+(remaining+enemies.filter(e=>e.hp>0&&!e.creeper).length)+' · '+difficultyNames[difficulty]:mode==='paused'?'已暫停':mode==='dead'?'防線失守':'準備開始';$('shopClock').textContent=blessings.pending()?'請選祝福 · 倒數暫停':Math.ceil(phaseTime)+' 秒';$('stats').textContent=Math.round(lastFPS)+' FPS · '+renderer.info.render.calls+' draws · S1.12';}
function radar(){const c=$('radar').getContext('2d'),size=180,k=5;c.clearRect(0,0,size,size);c.fillStyle='#152d37';c.fillRect(0,0,size,size);c.save();c.translate(90,90);c.strokeStyle='#86a49e';c.lineWidth=1;for(const w of D.walls){c.beginPath();w.outer.forEach(([x,z],i)=>{const a=(x-P.pos.x)*k,b=(z-P.pos.z)*k;i?c.lineTo(a,b):c.moveTo(a,b)});c.closePath();c.stroke();}for(const e of enemies)if(e.hp>0){c.fillStyle=e.tier===2?'#ffc45f':'#e78e80';c.beginPath();c.arc((e.pos.x-P.pos.x)*k,(e.pos.z-P.pos.z)*k,3,0,6.28);c.fill();}for(const b of barrels)if(!b.exploded){c.fillStyle='#bc7b4a';c.fillRect((b.pos.x-P.pos.x)*k-2,(b.pos.z-P.pos.z)*k-2,4,4);}c.rotate(-yaw);c.fillStyle='#a1f2d1';c.beginPath();c.moveTo(0,-7);c.lineTo(5,5);c.lineTo(-5,5);c.fill();c.restore();}
$('start').onclick=()=>{battleAudio.unlock();sound(420,.1,'sine');startGame();};$('practice').onclick=()=>startGame(true);$('restart').onclick=()=>startGame(practice);$('resume').onclick=resume;$('backMenu').onclick=leaveToMenu;$('leavePractice').onclick=leaveToMenu;$('shopBtn').onclick=openShop;$('closeShop').onclick=()=>closeShop();$('pauseBtn').onclick=()=>pauseGame();$('helpBtn').onclick=()=>{if(mode==='menu')return;pauseGame('Z 三段連斬、X 重斬、C 衝擊波、Alt 閃避；行動能量每秒回復10，擊倒回復10。按住跳躍可持續向上噴射；落地回充。按住 V 使用5m繩索，放開後冷卻3秒。受傷時中央箭頭會指向攻擊來源。敵人掉槍10秒消失，F拾取。困難模式敵人可附加屬性。');};$('floorBtn').onclick=()=>{if(mode==='menu'){notify('目前為 3F；1F／2F／7F 等待 layout 與遊戲導覽資料');return;}pauseGame('目前開放 3F。1F／2F／7F 尚無真實地圖，不會以3F冒充。後續可替換獨立樓層資料並重建導覽。');};$('foldTools').onclick=()=>{const f=$('tools').classList.toggle('folded');$('foldTools').textContent=f?'控制 ＋':'控制 −';$('foldTools').setAttribute('aria-expanded',String(!f));};
$('exportSave').onclick=()=>{const blob=new Blob([JSON.stringify({schema:'factory-shooter-xp-v1',xp},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='工廠防線_武器進度.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};$('importSave').onclick=()=>$('saveFile').click();$('saveFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const data=JSON.parse(await file.text());if(data.schema!=='factory-shooter-xp-v1'||!data.xp)throw Error('格式不符');const next={};for(const k in GUNS){const n=data.xp[k]??0;if(!Number.isFinite(n)||n<0||n>1e8)throw Error('經驗值錯誤');next[k]=n;}xp=next;save();$('saveStatus').textContent='進度匯入完成';}catch(e){$('saveStatus').textContent='匯入失敗：'+e.message;}finally{e.target.value='';}};
// Touch controls use independent pointer capture for movement, look and held actions.
let touchReset=()=>{};
if(mobile){
 document.body.classList.add('mobile');
 const controls=$('touchControls'),stick=$('moveStick'),knob=$('stickKnob');let moveId=null,lookId=null,lastX=0,lastY=0;const held=new Map();
 const allowed=()=>!shopOpen&&(mode==='buy'||mode==='combat');
 const key=(code,down)=>{if(down)keys.add(code);else{keys.delete(code);if(code==='Space')jumpLatch=false;if(code==='KeyV'){endHook();hookLatch=false;}}};
 const move=e=>{const r=stick.getBoundingClientRect(),x=(e.clientX-r.left-r.width/2)/(r.width*.35),y=(e.clientY-r.top-r.height/2)/(r.height*.35);key('KeyW',y<-.22);key('KeyS',y>.22);key('KeyA',x<-.22);key('KeyD',x>.22);key('ShiftLeft',Math.hypot(x,y)>.9);const len=Math.max(1,Math.hypot(x,y));knob.style.transform='translate('+x/len*30+'px,'+y/len*30+'px)';};
 stick.addEventListener('pointerdown',e=>{if(!allowed()||moveId!==null)return;e.preventDefault();moveId=e.pointerId;stick.setPointerCapture(e.pointerId);move(e);});
 stick.addEventListener('pointermove',e=>{if(e.pointerId===moveId){e.preventDefault();move(e);}});
 const stopMove=e=>{if(e.pointerId!==moveId)return;moveId=null;for(const k of ['KeyW','KeyS','KeyA','KeyD','ShiftLeft'])key(k,false);knob.style.transform='';};
 for(const ev of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(ev,stopMove);
 const canvas=renderer.domElement;
 canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||!allowed()||lookId!==null)return;e.preventDefault();lookId=e.pointerId;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(e.pointerId!==lookId||!allowed())return;e.preventDefault();const sensitivity=aim?.002:.004;yaw-=(e.clientX-lastX)*sensitivity;pitch=clamp(pitch-(e.clientY-lastY)*sensitivity,-1,.85);lastX=e.clientX;lastY=e.clientY;});
 for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,e=>{if(e.pointerId===lookId)lookId=null;});
 const actionsByName={reload:reload,pickup:pickup,door:()=>openNearbyDoor(P.pos,true),grenade:()=>throwItem('grenade'),flash:()=>throwItem('flash'),strike:()=>actions.strike(),heavy:()=>actions.strike(true),pulse:()=>actions.pulse(),dodge:()=>actions.dodge(),weapon:()=>switchGun(active===inventory.side?inventory.main:inventory.side)};
 const release=e=>{const name=held.get(e.pointerId);if(!name)return;held.delete(e.pointerId);if(name==='fire')fireHeld=false;else if(name==='aim')aim=false;else if(name==='jump')key('Space',false);else if(name==='hook')key('KeyV',false);else if(name==='crouch')key('ControlLeft',false);};
 for(const b of controls.querySelectorAll('button[data-action]')){b.addEventListener('pointerdown',e=>{if(!allowed())return;e.preventDefault();battleAudio.unlock();const name=b.dataset.action;b.setPointerCapture(e.pointerId);held.set(e.pointerId,name);if(name==='fire')fireHeld=true;else if(name==='aim')aim=true;else if(name==='jump')key('Space',true);else if(name==='hook')key('KeyV',true);else if(name==='crouch')key('ControlLeft',true);else actionsByName[name]?.();});for(const ev of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(ev,release);}
 touchReset=()=>{moveId=lookId=null;held.clear();keys.clear();fireHeld=aim=false;jumpLatch=hookLatch=false;endHook();knob.style.transform='';};
 addEventListener('blur',touchReset);addEventListener('orientationchange',touchReset);
 $('touchHint').hidden=false;
}

let dragging=false;renderer.domElement.addEventListener('mousedown',e=>{if(mobile)return;if(mode!=='combat'&&mode!=='buy')return;if(shopOpen)return;if(e.button===2){aim=true;return;}if(e.button===0){dragging=true;fireHeld=true;requestLock();}});addEventListener('mouseup',e=>{if(e.button===0){dragging=false;fireHeld=false;}if(e.button===2)aim=false;});renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());addEventListener('mousemove',e=>{if(shopOpen||(mode!=='combat'&&mode!=='buy'))return;if(document.pointerLockElement===renderer.domElement||dragging){const sensitivity=aim?.0013:.0024;yaw-=e.movementX*sensitivity;pitch=clamp(pitch-e.movementY*sensitivity,-1,.85);}});
addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.code==='Escape'){if(mode==='paused')resume();else if(mode==='combat'||mode==='buy')pauseGame();return;}if(mode!=='combat'&&mode!=='buy')return;if(shopOpen){if(e.code==='KeyB'&&!e.repeat)closeShop();return;}if(['Space','KeyW','KeyA','KeyS','KeyD','AltLeft','AltRight','ControlLeft','ControlRight'].includes(e.code))e.preventDefault();keys.add(e.code);if(e.repeat)return;if(e.code==='KeyB'){shopOpen?closeShop():openShop();return;}if(shopOpen)return;if(e.code==='Digit1')switchGun(inventory.main);if(e.code==='Digit2')switchGun(inventory.side);if(e.code==='KeyZ')actions.strike();if(e.code==='KeyX')actions.strike(true);if(e.code==='KeyC')actions.pulse();if(e.code==='AltLeft'||e.code==='AltRight')actions.dodge();if(e.code==='KeyR')reload();if(e.code==='KeyF')pickup();if(e.code==='KeyE')openNearbyDoor(P.pos,true);if(e.code==='KeyG')throwItem('grenade');if(e.code==='KeyQ')throwItem('flash');});addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space')jumpLatch=false;if(e.code==='KeyV'){endHook();hookLatch=false;}});
addEventListener('blur',()=>{if(mode==='combat'||mode==='buy')pauseGame();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&mode==='combat'&&!shopOpen)pauseGame();});addEventListener('beforeunload',save);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});
P.pos.copy(safePoint(P.pos));S.flow(P.pos);avatar.group.position.copy(P.pos);avatar.group.rotation.y=yaw;ammo.pistol=stats('pistol').mag;updateCamera(1);$('loading').hidden=true;let accumulated=0,uiTime=0;
function animate(){requestAnimationFrame(animate);const raw=Math.min(.1,clock.getDelta());accumulated+=raw;if(accumulated<1/CFG.targetFPS)return;const dt=accumulated;accumulated=0;lastFPS=lastFPS*.9+(1/dt)*.1;const n=Math.ceil(dt/.016);for(let i=0;i<n;i++)tick(dt/n);uiTime+=dt;if(uiTime>.1){updateHUD();radar();uiTime=0;}renderer.render(scene,camera);}animate();
window.factoryGame={version:CFG.version,ready:true,start:startGame,startPractice:()=>startGame(true),leave:leaveToMenu,pause:pauseGame,resume,buy:shopItem,closeShop:()=>closeShop(false),getState:()=>({version:CFG.version,paidUpgrades:JSON.parse(JSON.stringify(paidUpgrades)),agv:tactics.getAGV()?{hp:tactics.getAGV().hp,supplies:tactics.getAGV().supplies,pos:tactics.getAGV().pos.toArray()}:null,blessings:blessings.state(),armorMax:armorMax(),grenades,reviveUntil,action:actions.state(),playSeconds:gameTime,machines:selectedMachineNames.slice(),lootCount:loot.length,creepers:enemies.filter(e=>e.creeper&&e.hp>0).length,practice,mode,wave,remaining,enemies:enemies.filter(e=>e.hp>0).length,barrels:barrels.filter(b=>!b.exploded).length,drops:drops.length,hp:P.hp,armor:P.armor,fuel:P.fuel,money,active,ammo:{...ammo},inventory:{...inventory},xp:{...xp},player:P.pos.toArray(),cooldown:hookCD,buyTime:phaseTime,status:Object.keys(P.status),triangles:renderer.info.render.triangles}),config:CFG};
// Test harness is opt-in and not enabled during a normal user session.
if(window.__SHOOTER_TEST__)window.factoryGame.test={tickCreeper,clearCreepers,battleAudio,upgradeWeapon,getPaidUpgrades:()=>paidUpgrades,tickEffects,tactics,throwBossGrenade,moveActor,blessings,armorMax,resizePlayer,destruction,actions,refreshWaveLayout,loot,lootInReach,pickupLoot,playTimeText,factory:F,beginBuy,tick,keys,player:P,space:S,enemies,barrels,drops,projectiles,particles,tracers,scene,camera,avatar,fire,reload,throwItem,makeBarrel,explodeBarrel,damagePlayer,applyStatus,hurtEnemy,gain,stats,spawnEnemy,startHook,endHook,updateCamera,dropWeapon,pickup,flash,explosion,targetRay,getMode:()=>mode,setMode:v=>mode=v,setTime:v=>gameTime=v,getTime:()=>gameTime,setView:(a,b)=>{yaw=a;pitch=b;updateCamera(1)},switchGun,setFuel:v=>P.fuel=v};
})();
